### FILL RATE REPRO
## SANDRO JAKOSKA 2022

## LIBRARIES
#TEST

library(tidyverse)
library(DBI)
library(googlesheets4)
con2 <- dbConnect(odbc::odbc(), "reproreplica")

## START RESUME =========================================================================================

### TOTAL PEDIDOS

totalpedid <- dbGetQuery(con2,"
WITH  
RESULT1 AS (SELECT P.ID_PEDIDO,AP.APCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
WHERE 

/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND
P.EMPCODIGO=1
AND TPCODIGO IN (1,2,3,4,6,7,12,14)
AND PEDSITPED IN ('A','F') ),

RESULT3 AS (SELECT P.ID_PEDIDO,AP.APCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
WHERE 

/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND
P.EMPCODIGO=3
AND TPCODIGO IN (1,3)
AND PEDSITPED IN ('A','F') ),

RESULT4 AS (SELECT P.ID_PEDIDO,AP.APCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
WHERE 

/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND
P.EMPCODIGO=4
AND TPCODIGO IN (1,3)
AND PEDSITPED IN ('A','F') ),

RESULT5 AS (SELECT P.ID_PEDIDO,AP.APCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
WHERE 

/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND
P.EMPCODIGO=5
AND TPCODIGO IN (1,3)
AND PEDSITPED IN ('A','F') ),

RESULT8 AS (SELECT P.ID_PEDIDO,AP.APCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
WHERE 

/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND
P.EMPCODIGO=8
AND TPCODIGO IN (1,3,9)
AND PEDSITPED IN ('A','F')),

RESULT9 AS (SELECT P.ID_PEDIDO,AP.APCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
WHERE 

/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND
P.EMPCODIGO=1
AND TPCODIGO IN (10,11)
AND PEDSITPED IN ('A','F'))

 /* SELECT BY EMP */ 
 
 SELECT 'MATRIZ' EMPRESA, 'TOTAL PEDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT1 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 ) UNION
    
      
    SELECT 'JOINVILLE' EMPRESA, 'TOTAL PEDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT3 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )UNION
      
     SELECT 'CRICIUMA' EMPRESA, 'TOTAL PEDIDOS' INDICADOR, COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT4 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )UNION
      
      SELECT 'CHAPECO' EMPRESA, 'TOTAL PEDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT5 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )UNION
      
      SELECT 'BALNEARIO C' EMPRESA, 'TOTAL PEDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT8 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )UNION
      
      SELECT 'MATRIZ' EMPRESA, 'TOTAL PEDIDOS CONTROL' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT9 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
") 


totalpednatend <- dbGetQuery(con2,"
WITH 
RESULT1 AS (SELECT P.ID_PEDIDO,AP.APCODIGO, LP.LPCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 

/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND
P.EMPCODIGO=1
AND TPCODIGO IN (1,2,3,4,6,7,12,14)
AND PEDSITPED IN ('A','F') ),


RESULT3 AS (SELECT P.ID_PEDIDO,AP.APCODIGO, LP.LPCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 


/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND
P.EMPCODIGO=3
AND TPCODIGO IN (1,3)
AND PEDSITPED IN ('A','F') ),

RESULT4 AS (SELECT P.ID_PEDIDO,AP.APCODIGO, LP.LPCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 

/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND
P.EMPCODIGO=4
AND TPCODIGO IN (1,3)
AND PEDSITPED IN ('A','F') ),

RESULT5 AS (SELECT P.ID_PEDIDO,AP.APCODIGO, LP.LPCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 

/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND
P.EMPCODIGO=5
AND TPCODIGO IN (1,3)
AND PEDSITPED IN ('A','F') ),

RESULT8 AS (SELECT P.ID_PEDIDO,AP.APCODIGO, LP.LPCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 

/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND
P.EMPCODIGO=8
AND TPCODIGO IN (1,3,9)
AND PEDSITPED IN ('A','F') ),

RESULT9 AS (SELECT P.ID_PEDIDO,AP.APCODIGO, LP.LPCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 

/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------


AND
P.EMPCODIGO=1
AND TPCODIGO IN (10,11)
AND PEDSITPED IN ('A','F') )
 
 SELECT 'MATRIZ' EMPRESA, 'PEDIDOS NAO ATENDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT1 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 ) UNION
      
      
    SELECT 'JOINVILLE' EMPRESA, 'PEDIDOS NAO ATENDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT3 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 ) UNION
      
     SELECT 'CRICIUMA' EMPRESA, 'PEDIDOS NAO ATENDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT4 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 ) UNION
      
      SELECT 'CHAPECO' EMPRESA, 'PEDIDOS NAO ATENDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT5 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 ) UNION
      
      SELECT 'BALNEARIO C' EMPRESA, 'PEDIDOS NAO ATENDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT8 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )UNION
      
      SELECT 'MATRIZ' EMPRESA, 'PEDIDOS CONTROL NAO ATENDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT9 R
   WHERE
   
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
")


control <- dbGetQuery(con2,"
  EXECUTE BLOCK RETURNS (EMPRESA VARCHAR(30),INDICADOR VARCHAR(30),TOTAL DECIMAL(15,2))
  
  AS DECLARE VARIABLE CLIENTE INT;
  
  BEGIN
  FOR
  
  SELECT DISTINCT CLICODIGO
  FROM CLIEN
  WHERE CLICODIGO IN (495,1065,81,5)

  INTO :CLIENTE
  DO
  BEGIN
  FOR
  
  SELECT 
  CASE 
  WHEN CLICODIGO=495 THEN 'JOINVILLE'
  WHEN CLICODIGO=1065 THEN 'CRICIUMA'
  WHEN CLICODIGO=81 THEN 'CHAPECO'
  WHEN CLICODIGO=5 THEN 'BALNEARIO C'
  END FILIAL,
  COUNT (DISTINCT (P.ID_PEDIDO)) TOTAL,'CONTROL' INDICADOR
FROM PEDID P
WHERE P.PEDSITPED IN ('A','F')
AND P.CLICODIGO = :CLIENTE AND P.TPCODIGO IN ('10','11')
AND 

/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND EXISTS (SELECT 1 FROM PEDROTEIRO PR1 WHERE PR1.ALXCODIGO = 1 AND PR1.ID_PEDIDO = P.ID_PEDIDO)
AND NOT EXISTS (SELECT 1 FROM PEDROTEIRO PR2 WHERE PR2.ALXCODIGO IN ('15','16','10','9','38','40','6') 
AND PR2.ID_PEDIDO = P.ID_PEDIDO) GROUP BY 1
  
  INTO :EMPRESA,:TOTAL,:INDICADOR
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END 
  
  ")


## RESUMO PEDIDOS

fillrate_resumo <- rbind(totalpedid,totalpednatend,control) %>%
  mutate(DATA=Sys.Date()) %>% as.data.frame()


## CALC FILL RATE =================================================================


## CALCULO FILIAIS 

fillrate_calc_filiais <- fillrate_resumo %>% 
  filter(!str_detect(EMPRESA,"MATRIZ")) %>% 
  group_by(EMPRESA) %>% 
  mutate(INDICADOR=trimws(INDICADOR)) %>% 
  summarize(VALOR=(1-((sum(TOTAL[INDICADOR=='CONTROL'])+sum(TOTAL[INDICADOR=='PEDIDOS NAO ATENDIDOS']))/
                        sum(TOTAL[INDICADOR=='TOTAL PEDIDOS'])))*100) %>%
  mutate(VALOR=round(VALOR,2)) %>% mutate(INDICADOR="FILL RATE: CONTROL + NAO ATENDIDOS x TOTAL PEDIDOS") %>% 
  mutate(DATA=Sys.Date()) %>% as.data.frame() %>% .[,c(1,3,2,4)] 


## CALCULO MATRIZ

fillrate_calc_matriz_1 <- fillrate_resumo %>%  
  filter(str_detect(EMPRESA,"MATRIZ"))%>% 
  group_by(EMPRESA) %>% 
  mutate(INDICADOR=trimws(INDICADOR)) %>% 
  summarize(VALOR=(1-((sum(TOTAL[INDICADOR=='PEDIDOS NAO ATENDIDOS']))/sum(TOTAL[INDICADOR=='TOTAL PEDIDOS'])))*100) %>%
  mutate(VALOR=round(VALOR,2)) %>% mutate(INDICADOR="FILL RATE: NAO ATENDIDOS x TOTAL") %>% 
  mutate(DATA=Sys.Date()) %>% as.data.frame() %>% .[,c(1,3,2,4)] 

fillrate_calc_matriz_2 <- fillrate_resumo %>%  
  mutate(INDICADOR=trimws(INDICADOR)) %>% 
  filter(str_detect(EMPRESA,"MATRIZ"))%>% 
  group_by(EMPRESA) %>%
  summarize(VALOR=(1-((sum(TOTAL[INDICADOR=='PEDIDOS CONTROL NAO ATENDIDOS']))/sum(TOTAL[INDICADOR=='TOTAL PEDIDOS CONTROL'])))*100) %>%
  mutate(VALOR=round(VALOR,2)) %>% mutate(INDICADOR="FILL RATE: CONTROL NAO ATENDIDOS x CONTROL TOTAL") %>% 
  mutate(DATA=Sys.Date()) %>% as.data.frame() %>% .[,c(1,3,2,4)] 

fillrate_calc_matriz_3 <- fillrate_resumo %>%  
  mutate(INDICADOR=trimws(INDICADOR)) %>% 
  filter(str_detect(EMPRESA,"MATRIZ"))%>% 
  group_by(EMPRESA) %>%
  summarize(VALOR=(1-((sum(TOTAL[INDICADOR=='PEDIDOS CONTROL NAO ATENDIDOS']))/sum(TOTAL[INDICADOR=='TOTAL PEDIDOS'])))*100) %>%
  mutate(VALOR=round(VALOR,2)) %>% mutate(INDICADOR="FILL RATE: CONTROL NAO ATENDIDOS x TOTAL PEDIDOS") %>% 
  mutate(DATA=Sys.Date()) %>% as.data.frame() %>% .[,c(1,3,2,4)] 


fill_rate_calc <- union_all(fillrate_calc_filiais,fillrate_calc_matriz_1) %>% 
  union_all(.,fillrate_calc_matriz_2) %>% 
  union_all(.,fillrate_calc_matriz_3) %>% rename(TOTAL=VALOR)

## ADD RESUME AND CALC THEN SAVE

fillrate_resumo2 <- union_all(fillrate_resumo,fill_rate_calc) 

filewd_fillrate_resumo <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_resumo2","_",format(Sys.Date(),"%d_%m_%y"),".RData")

save(fillrate_resumo2,file =filewd_fillrate_resumo)

## GET SAVED DATA

fillrate_repro <- get(load("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_repro.RData"))


## ADD SAVED DATA TO CURRENT ONE

fillrate_repro <- union_all(fillrate_repro,fillrate_resumo2) %>% 
  arrange(desc(DATA)) %>% distinct() %>% as.data.frame()

## REGISTER GOOGLE SHEETS

range_write("1qC12w2k2mZ2RiF_Xsl27C4a3NztilFEgr7qT3sBPYJg",
            data=fillrate_repro,sheet = "RESUMO",
            range = "A1",reformat = FALSE)

## SAVE FINAL BASE

save(fillrate_repro,file = "C:\\Users\\Repro\\Documents\\LOGISTICA\\FILLRATE\\BASES\\fillrate_repro.RData" )



## END RESUME =========================================================================================

## START ORDER DETAILS =========================================================================================

# MATRIZ

fillrate_mp_matriz  <- dbGetQuery(con2,"
  EXECUTE BLOCK RETURNS (
                        EMPRESA VARCHAR(30),
                         INDICADOR VARCHAR(30),
                          PEDIDO INT,
                           EMISSAO DATE,   
                            MATERIAL VARCHAR(100),
                             NOME VARCHAR(100),
                              UN VARCHAR(30), 
                               SEQ VARCHAR(30),
                                CHAVE VARCHAR(30),
                                 DESCRICAO_CHAVE VARCHAR(100),
                                  QTD DECIMAL(15,2))
  
  AS DECLARE VARIABLE ID_PEDIDO INT;
  
  BEGIN
  FOR
  
  /* FILTRO PEDIDOS NAO ATENDIDOS MATRIZ */ 
  
WITH 
RESULT1 AS (SELECT DISTINCT P.ID_PEDIDO,PEDDTEMIS,AP.APCODIGO,LP.LPCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE

/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND P.EMPCODIGO=1
AND TPCODIGO IN (1,2,3,4,6,7,12,14)
AND PEDSITPED IN ('A','F'))
 
 SELECT DISTINCT R.ID_PEDIDO
   FROM RESULT1 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )

  INTO :ID_PEDIDO 
  DO
  BEGIN
  FOR

  /* FILTRO PEDIDOS NAO ATENDIDOS MATRIZ */ 
  
  WITH PED AS (SELECT ID_PEDIDO,PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO),
  
      PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM PRODU WHERE PROSITUACAO='A' AND PROTIPO NOT IN ('T','M','S','C'))

  
  SELECT
   'MATRIZ' EMPRESA,
   'PEDIDOS NAO ATENDIDOS' INDICADOR,
   ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   RP.PROCODIGO MATERIAL , 
    RP.RQPDESCRICAO NOME , 
     PD.PROUN UN , 
      RQPSEQ,
      PD.PROCODIGO2 CHAVE,
      (SELECT DISTINCT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PD.PROCODIGO2) DESCRICAO_CHAVE,
      RP.RQPQTDADE QTD    
      FROM PEDCELPDCAO PCP
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO,PROCODIGO2,PRODESCRICAO,PROUN FROM PRODU WHERE PROTIPO NOT IN ('T','S')) PD ON PD.PROCODIGO = RP.PROCODIGO

WHERE
PCP.ID_PEDIDO = :ID_PEDIDO AND
RP.PROCODIGO IS NOT NULL UNION

SELECT
  'MATRIZ' EMPRESA,
  'PEDIDOS NAO ATENDIDOS' INDICADOR,
   PRD.ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   PRD.PROCODIGO MATERIAL , 
    PDPDESCRICAO NOME , 
      (SELECT DISTINCT PROUN FROM PRODU WHERE PROCODIGO=CHAVE ) UN,
      '' RQPSEQ,
      CHAVE CHAVE,
      (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE ) DESCRICAO_CHAVE,
      PRD.PDPQTDADE QTD    
      FROM PDPRD PRD
      INNER JOIN PED ON PRD.ID_PEDIDO=PED.ID_PEDIDO
      INNER JOIN PROD P ON PRD.PROCODIGO=P.PROCODIGO
  
  INTO :EMPRESA,:INDICADOR,:PEDIDO,:EMISSAO, :MATERIAL,:NOME, :UN, :SEQ,:CHAVE, :DESCRICAO_CHAVE,:QTD
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END 
  
  ")

#JOINVILLE
fillrate_mp_joinville  <- dbGetQuery(con2,"
  EXECUTE BLOCK RETURNS ( 
                      EMPRESA VARCHAR(30),
                       INDICADOR VARCHAR(30), 
                        PEDIDO INT,
                         EMISSAO DATE,   
                          MATERIAL VARCHAR(100),
                           NOME VARCHAR(100),
                            UN VARCHAR(30), 
                             SEQ VARCHAR(30),
                               CHAVE VARCHAR(30),
                                DESCRICAO_CHAVE VARCHAR(100),
                                 QTD DECIMAL(15,2))
  
  AS DECLARE VARIABLE ID_PEDIDO INT;
  
  BEGIN
  FOR
  

 /* FILTRO PEDIDOS NAO ATENDIDOS JOINVILLE */ 
  
WITH 
RESULT3 AS (SELECT DISTINCT P.ID_PEDIDO,PEDDTEMIS,AP.APCODIGO,LP.LPCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 


/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND
P.EMPCODIGO=3
AND TPCODIGO IN (1,3)
AND PEDSITPED IN ('A','F'))
 
 SELECT DISTINCT R.ID_PEDIDO
   FROM RESULT3 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )

  INTO :ID_PEDIDO 
  DO
  BEGIN
  FOR
  
 /* LENTES COM PRODUCAO */ 
  
  WITH PED AS (SELECT ID_PEDIDO,PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO),
  
  PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM PRODU WHERE PROSITUACAO='A' AND PROTIPO NOT IN ('T','M','S','C'))

  
  SELECT
  'JOINVILLE' EMPRESA,
  'PEDIDOS NAO ATENDIDOS' INDICADOR,
   ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   RP.PROCODIGO MATERIAL , 
    RP.RQPDESCRICAO NOME , 
     PD.PROUN UN,
      RQPSEQ,
      PD.PROCODIGO2 CHAVE,
      (SELECT DISTINCT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PD.PROCODIGO2) DESCRICAO_CHAVE,
      RP.RQPQTDADE QTD    
      FROM PEDCELPDCAO PCP
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO,PROCODIGO2,PRODESCRICAO,PROUN FROM PRODU WHERE PROTIPO NOT IN ('T','S')) PD ON PD.PROCODIGO = RP.PROCODIGO

WHERE
PCP.ID_PEDIDO = :ID_PEDIDO AND
RP.PROCODIGO IS NOT NULL UNION

/* SELECIONA LENTES ACABADAS */

SELECT
  'JOINVILLE' EMPRESA,
  'PEDIDOS NAO ATENDIDOS' INDICADOR,
   PRD.ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   PRD.PROCODIGO MATERIAL , 
    PDPDESCRICAO NOME , 
      (SELECT DISTINCT PROUN FROM PRODU WHERE PROCODIGO=CHAVE ) UN,
      '' RQPSEQ,
      CHAVE CHAVE,
      (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE ) DESCRICAO_CHAVE,
      PRD.PDPQTDADE QTD    
      FROM PDPRD PRD
      INNER JOIN PED ON PRD.ID_PEDIDO=PED.ID_PEDIDO
      INNER JOIN PROD P ON PRD.PROCODIGO=P.PROCODIGO
  
  INTO :EMPRESA,:INDICADOR,:PEDIDO,:EMISSAO, :MATERIAL,:NOME, :UN, :SEQ,:CHAVE, :DESCRICAO_CHAVE,:QTD
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END 
  
  ")

#CRICIUMA
fillrate_mp_criciuma  <- dbGetQuery(con2,"
 EXECUTE BLOCK RETURNS ( 
                      EMPRESA VARCHAR(30), 
                       INDICADOR VARCHAR(30),
                        PEDIDO INT,
                          EMISSAO DATE,   
                            MATERIAL VARCHAR(100),
                             NOME VARCHAR(100),
                              UN VARCHAR(30), 
                               SEQ VARCHAR(30),
                                CHAVE VARCHAR(30),
                                 DESCRICAO_CHAVE VARCHAR(100),
                                  QTD DECIMAL(15,2))
  
  AS DECLARE VARIABLE ID_PEDIDO INT;
  
  BEGIN
  FOR
  
    /* FILTRO PEDIDOS NAO ATENDIDOS CRICIUMA */
  
WITH 
RESULT1 AS (SELECT DISTINCT P.ID_PEDIDO,PEDDTEMIS,AP.APCODIGO,LP.LPCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 

/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------


AND
P.EMPCODIGO=4
AND TPCODIGO IN (1,2,3,4,6,7,12,14)
AND PEDSITPED IN ('A','F'))
 
 SELECT DISTINCT R.ID_PEDIDO
   FROM RESULT1 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )

  INTO :ID_PEDIDO 
  DO
  BEGIN
  FOR
  
   /* LENTES COM PRODUCAO */ 
  
  WITH PED AS (SELECT ID_PEDIDO,PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO),
  
  PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM 
  PRODU WHERE PROSITUACAO='A' AND PROTIPO NOT IN ('T','M','S','C'))

  
  SELECT
   'CRICIUMA' EMPRESA,
   'PEDIDOS NAO ATENDIDOS' INDICADOR,
   ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   RP.PROCODIGO MATERIAL , 
    RP.RQPDESCRICAO NOME , 
     PD.PROUN UN , 
      RQPSEQ,
      PD.PROCODIGO2 CHAVE,
      (SELECT DISTINCT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PD.PROCODIGO2) DESCRICAO_CHAVE,
      RP.RQPQTDADE QTD    
      FROM PEDCELPDCAO PCP
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO,PROCODIGO2,PRODESCRICAO,PROUN FROM PRODU WHERE PROTIPO NOT IN ('T','S')) PD ON PD.PROCODIGO = RP.PROCODIGO

WHERE
PCP.ID_PEDIDO = :ID_PEDIDO AND
RP.PROCODIGO IS NOT NULL UNION

/* SELECIONA LENTES ACABADAS */

SELECT
  'CRICIUMA' EMPRESA,
  'PEDIDOS NAO ATENDIDOS' INDICADOR,
   PRD.ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   PRD.PROCODIGO MATERIAL , 
    PDPDESCRICAO NOME , 
      (SELECT DISTINCT PROUN FROM PRODU WHERE PROCODIGO=CHAVE ) UN,
      '' RQPSEQ,
      CHAVE CHAVE,
      (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE ) DESCRICAO_CHAVE,
      PRD.PDPQTDADE QTD    
      FROM PDPRD PRD
      INNER JOIN PED ON PRD.ID_PEDIDO=PED.ID_PEDIDO
      INNER JOIN PROD P ON PRD.PROCODIGO=P.PROCODIGO
  
  INTO :EMPRESA,:INDICADOR,:PEDIDO,:EMISSAO, :MATERIAL,:NOME, :UN,:SEQ,:CHAVE, :DESCRICAO_CHAVE,:QTD
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END 
  
  ")

#CHAPECO
fillrate_mp_chapeco  <- dbGetQuery(con2,"
 EXECUTE BLOCK RETURNS ( 
                      EMPRESA VARCHAR(30),
                       INDICADOR VARCHAR(30), 
                        PEDIDO INT,
                          EMISSAO DATE,   
                           MATERIAL VARCHAR(100),
                             NOME VARCHAR(100),
                              UN VARCHAR(30), 
                               SEQ VARCHAR(30),
                                CHAVE VARCHAR(30),
                                 DESCRICAO_CHAVE VARCHAR(100),
                                  QTD DECIMAL(15,2))
  
  AS DECLARE VARIABLE ID_PEDIDO INT;
  
  BEGIN
  FOR
  
    /* FILTRO PEDIDOS NAO ATENDIDOS CHAPECO */
  
WITH 
RESULT1 AS (SELECT DISTINCT P.ID_PEDIDO,PEDDTEMIS,AP.APCODIGO,LP.LPCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 

/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND
P.EMPCODIGO=5
AND TPCODIGO IN (1,2,3,4,6,7,12,14)
AND PEDSITPED IN ('A','F'))
 
 SELECT DISTINCT R.ID_PEDIDO
   FROM RESULT1 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )

  INTO :ID_PEDIDO 
  DO
  BEGIN
  FOR
  
   /* LENTES COM PRODUCAO */ 
  
  WITH PED AS (SELECT ID_PEDIDO,PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO),
  
  PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM 
  PRODU WHERE PROSITUACAO='A' AND PROTIPO NOT IN ('T','M','S','C'))
  
  SELECT
   'CHAPECO' EMPRESA,
   'PEDIDOS NAO ATENDIDOS' INDICADOR,
   ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO,
   RP.PROCODIGO MATERIAL , 
    RP.RQPDESCRICAO NOME , 
     PD.PROUN UN , 
      RQPSEQ,
      PD.PROCODIGO2 CHAVE,
      (SELECT DISTINCT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PD.PROCODIGO2) DESCRICAO_CHAVE,
      RP.RQPQTDADE QTD    
      FROM PEDCELPDCAO PCP
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO,PROCODIGO2,PRODESCRICAO,PROUN FROM PRODU WHERE PROTIPO NOT IN ('T','S')) PD ON PD.PROCODIGO = RP.PROCODIGO

WHERE
PCP.ID_PEDIDO = :ID_PEDIDO AND
RP.PROCODIGO IS NOT NULL UNION

/* SELECIONA LENTES ACABADAS */

SELECT
  'CRICIUMA' EMPRESA,
  'PEDIDOS NAO ATENDIDOS' INDICADOR,
   PRD.ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   PRD.PROCODIGO MATERIAL , 
    PDPDESCRICAO NOME , 
      (SELECT DISTINCT PROUN FROM PRODU WHERE PROCODIGO=CHAVE ) UN,
      '' RQPSEQ,
      CHAVE CHAVE,
      (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE ) DESCRICAO_CHAVE,
      PRD.PDPQTDADE QTD    
      FROM PDPRD PRD
      INNER JOIN PED ON PRD.ID_PEDIDO=PED.ID_PEDIDO
      INNER JOIN PROD P ON PRD.PROCODIGO=P.PROCODIGO
  
  INTO :EMPRESA,:INDICADOR,:PEDIDO,:EMISSAO, :MATERIAL,:NOME, :UN,:SEQ,:CHAVE, :DESCRICAO_CHAVE,:QTD
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END 
  
  ")

#BC
fillrate_mp_bc  <- dbGetQuery(con2,"
 EXECUTE BLOCK RETURNS ( 
                      EMPRESA VARCHAR(30), 
                       INDICADOR VARCHAR(30), 
                        PEDIDO INT,
                          EMISSAO DATE,   
                            MATERIAL VARCHAR(100),
                             NOME VARCHAR(100),
                              UN VARCHAR(30), 
                               SEQ VARCHAR(30),
                                CHAVE VARCHAR(30),
                                 DESCRICAO_CHAVE VARCHAR(100),
                                  QTD DECIMAL(15,2))
  
  AS DECLARE VARIABLE ID_PEDIDO INT;
  
  BEGIN
  FOR
  
    /* FILTRO PEDIDOS NAO ATENDIDOS BC */
  
WITH 
RESULT1 AS (SELECT DISTINCT P.ID_PEDIDO,PEDDTEMIS,AP.APCODIGO,LP.LPCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 


/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND
P.EMPCODIGO=8
AND TPCODIGO IN (1,2,3,4,6,7,12,14)
AND PEDSITPED IN ('A','F'))
 
 SELECT DISTINCT R.ID_PEDIDO
   FROM RESULT1 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )

  INTO :ID_PEDIDO 
  DO
  BEGIN
  FOR
  
   /* LENTES COM PRODUCAO */ 
  
  WITH PED AS (SELECT ID_PEDIDO,PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO),
  
  PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM 
  PRODU WHERE PROSITUACAO='A' AND PROTIPO NOT IN ('T','M','S','C'))
  
  SELECT
   'BC' EMPRESA,
   'PEDIDOS NAO ATENDIDOS' INDICADOR,
   ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   RP.PROCODIGO MATERIAL , 
    RP.RQPDESCRICAO NOME , 
     PD.PROUN UN,
      RQPSEQ,
      PD.PROCODIGO2 CHAVE,
      (SELECT DISTINCT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PD.PROCODIGO2) DESCRICAO_CHAVE,
      RP.RQPQTDADE QTD    
      FROM PEDCELPDCAO PCP
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO,PROCODIGO2,PRODESCRICAO,PROUN FROM PRODU WHERE PROTIPO NOT IN ('T','S')) PD ON PD.PROCODIGO = RP.PROCODIGO

WHERE
PCP.ID_PEDIDO = :ID_PEDIDO AND
RP.PROCODIGO IS NOT NULL 

UNION

/* SELECIONA LENTES ACABADAS */

SELECT
  'CRICIUMA' EMPRESA,
  'PEDIDOS NAO ATENDIDOS' INDICADOR,
   PRD.ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   PRD.PROCODIGO MATERIAL , 
    PDPDESCRICAO NOME , 
      (SELECT DISTINCT PROUN FROM PRODU WHERE PROCODIGO=CHAVE ) UN,
      '' RQPSEQ,
      CHAVE CHAVE,
      (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE ) DESCRICAO_CHAVE,
      PRD.PDPQTDADE QTD    
      FROM PDPRD PRD
      INNER JOIN PED ON PRD.ID_PEDIDO=PED.ID_PEDIDO
      INNER JOIN PROD P ON PRD.PROCODIGO=P.PROCODIGO
  
  INTO :EMPRESA,:INDICADOR,:PEDIDO,:EMISSAO, :MATERIAL,:NOME,:UN,:SEQ,:CHAVE, :DESCRICAO_CHAVE,:QTD
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END 
  
  ")



# CONTROL
fillrate_mp_control  <- dbGetQuery(con2,"
 EXECUTE BLOCK RETURNS ( 
                      EMPRESA VARCHAR(30), 
                       INDICADOR VARCHAR(30), 
                        PEDIDO INT,
                          EMISSAO DATE,   
                            MATERIAL VARCHAR(100),
                             NOME VARCHAR(100),
                              UN VARCHAR(30), 
                               SEQ VARCHAR(30),
                                CHAVE VARCHAR(30),
                                 DESCRICAO_CHAVE VARCHAR(100),
                                  QTD DECIMAL(15,2))
  
  AS DECLARE VARIABLE ID_PEDIDO INT;
  
  BEGIN
  FOR
  
    /* FILTRO PEDIDOS CONTROL */
  
SELECT DISTINCT
   PE.ID_PEDIDO
FROM PEDID PE
WHERE 

/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND PE.PEDSITPED IN ('A','F')
AND PE.CLICODIGO IN (495,1065,81,5) AND PE.TPCODIGO IN ('10','11')
AND EXISTS (SELECT 1 FROM PEDROTEIRO PR1 WHERE PR1.ALXCODIGO = 1 AND PR1.ID_PEDIDO = PE.ID_PEDIDO)
AND NOT EXISTS (SELECT 1 FROM PEDROTEIRO PR2 WHERE PR2.ALXCODIGO IN ('15','16','10','9','38','40','6') 
AND PR2.ID_PEDIDO = PE.ID_PEDIDO) 

  INTO :ID_PEDIDO 
  DO
  BEGIN
  FOR
  
   /* LENTES COM PRODUCAO */ 
  
  WITH PED AS (SELECT ID_PEDIDO,CLICODIGO PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO),
  
  PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM 
  PRODU WHERE PROSITUACAO='A' AND PROTIPO NOT IN ('T','M','S','C'))
  
  SELECT
    (SELECT CASE 
  WHEN CLICODIGO=495 THEN 'JOINVILLE'
  WHEN CLICODIGO=1065 THEN 'CRICIUMA'
  WHEN CLICODIGO=81 THEN 'CHAPECO'
  WHEN CLICODIGO=5 THEN 'BALNEARIO C'
  END FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMPRESA,
   'PEDIDOS CONTROL FILIAIS' INDICADOR,
   ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   RP.PROCODIGO MATERIAL , 
    RP.RQPDESCRICAO NOME , 
     PD.PROUN UN,
      RQPSEQ,
      PD.PROCODIGO2 CHAVE,
      (SELECT DISTINCT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PD.PROCODIGO2) DESCRICAO_CHAVE,
      RP.RQPQTDADE QTD    
      FROM PEDCELPDCAO PCP
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO,PROCODIGO2,PRODESCRICAO,PROUN FROM PRODU WHERE PROTIPO NOT IN ('T','S')) PD ON PD.PROCODIGO = RP.PROCODIGO

WHERE
PCP.ID_PEDIDO = :ID_PEDIDO AND
RP.PROCODIGO IS NOT NULL 

UNION

/* SELECIONA LENTES ACABADAS */

SELECT
  
 (SELECT CASE 
  WHEN CLICODIGO=495 THEN 'JOINVILLE'
  WHEN CLICODIGO=1065 THEN 'CRICIUMA'
  WHEN CLICODIGO=81 THEN 'CHAPECO'
  WHEN CLICODIGO=5 THEN 'BALNEARIO C'
  END FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMPRESA,
  
  'PEDIDOS CONTROL' INDICADOR,
   PRD.ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   PRD.PROCODIGO MATERIAL , 
    PDPDESCRICAO NOME , 
      (SELECT DISTINCT PROUN FROM PRODU WHERE PROCODIGO=CHAVE ) UN,
      '' RQPSEQ,
      CHAVE CHAVE,
      (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE ) DESCRICAO_CHAVE,
      PRD.PDPQTDADE QTD    
      FROM PDPRD PRD
      INNER JOIN PED ON PRD.ID_PEDIDO=PED.ID_PEDIDO
      INNER JOIN PROD P ON PRD.PROCODIGO=P.PROCODIGO
  
  INTO :EMPRESA,:INDICADOR,:PEDIDO,:EMISSAO, :MATERIAL,:NOME,:UN,:SEQ,:CHAVE, :DESCRICAO_CHAVE,:QTD
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END 
  
  ")

# CONTROL NOT ATEND MATRIZ


fillrate_mp_control_matriz  <- dbGetQuery(con2,"
  EXECUTE BLOCK RETURNS (
                        EMPRESA VARCHAR(30),
                         INDICADOR VARCHAR(30),
                          PEDIDO INT,
                           EMISSAO DATE,   
                            MATERIAL VARCHAR(100),
                             NOME VARCHAR(100),
                              UN VARCHAR(30), 
                               SEQ VARCHAR(30),
                                CHAVE VARCHAR(30),
                                 DESCRICAO_CHAVE VARCHAR(100),
                                  QTD DECIMAL(15,2))
  
  AS DECLARE VARIABLE ID_PEDIDO INT;
  
  BEGIN
  FOR
  
  /* FILTRO PEDIDOS NAO ATENDIDOS CONTROL MATRIZ */ 
  
WITH 
RESULT11 AS (SELECT DISTINCT P.ID_PEDIDO,PEDDTEMIS,AP.APCODIGO,LP.LPCODIGO FROM
PEDID P
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 

/* DATES */ 

PEDDTEMIS >=
DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND
P.EMPCODIGO=1
AND TPCODIGO IN (10,11)
AND PEDSITPED IN ('A','F'))
 
 SELECT DISTINCT R.ID_PEDIDO
   FROM RESULT11 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )

  INTO :ID_PEDIDO 
  DO
  BEGIN
  FOR

  /* FILTRO PEDIDOS NAO ATENDIDOS MATRIZ */ 
  
  WITH PED AS (SELECT ID_PEDIDO,PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO),
  
      PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM PRODU WHERE PROSITUACAO='A' AND PROTIPO NOT IN ('T','M','S','C'))

  
  SELECT
   'MATRIZ' EMPRESA,
   'PEDIDOS CONTROL NAO ATENDIDOS' INDICADOR,
   ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   RP.PROCODIGO MATERIAL , 
    RP.RQPDESCRICAO NOME , 
     PD.PROUN UN , 
      RQPSEQ,
      PD.PROCODIGO2 CHAVE,
      (SELECT DISTINCT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PD.PROCODIGO2) DESCRICAO_CHAVE,
      RP.RQPQTDADE QTD    
      FROM PEDCELPDCAO PCP
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO,PROCODIGO2,PRODESCRICAO,PROUN FROM PRODU WHERE PROTIPO NOT IN ('T','S')) PD ON PD.PROCODIGO = RP.PROCODIGO

WHERE
PCP.ID_PEDIDO = :ID_PEDIDO AND
RP.PROCODIGO IS NOT NULL UNION

SELECT
  'MATRIZ' EMPRESA,
  'PEDIDOS CONTROL NAO ATENDIDOS' INDICADOR,
   PRD.ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   PRD.PROCODIGO MATERIAL , 
    PDPDESCRICAO NOME , 
      (SELECT DISTINCT PROUN FROM PRODU WHERE PROCODIGO=CHAVE ) UN,
      '' RQPSEQ,
      CHAVE CHAVE,
      (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE ) DESCRICAO_CHAVE,
      PRD.PDPQTDADE QTD    
      FROM PDPRD PRD
      INNER JOIN PED ON PRD.ID_PEDIDO=PED.ID_PEDIDO
      INNER JOIN PROD P ON PRD.PROCODIGO=P.PROCODIGO
  
  INTO :EMPRESA,:INDICADOR,:PEDIDO,:EMISSAO, :MATERIAL,:NOME, :UN, :SEQ,:CHAVE, :DESCRICAO_CHAVE,:QTD
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END 
  
  ")

# ADD ALL BLOCKS

fillrate_mp_emp <- union_all(fillrate_mp_matriz,fillrate_mp_joinville) %>% 
  union_all(.,fillrate_mp_criciuma) %>% 
  union_all(.,fillrate_mp_chapeco) %>% 
  union_all(.,fillrate_mp_bc) %>% 
  union_all(.,fillrate_mp_control) %>% 
  union_all(.,fillrate_mp_control_matriz) %>% 
  mutate(DATA=Sys.Date()) %>% distinct() %>% as.data.frame()

# SAVE CURRENT DAY

filewd_emp <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_mp_emp","_",format(Sys.Date(),"%d_%m_%y"),".RData")

save(fillrate_mp_emp,file =filewd_emp)


# AGGREG MP AND SUM

fillrate_mp_emp_resumo <- fillrate_mp_emp %>% group_by(INDICADOR,CHAVE,DESCRICAO_CHAVE) %>% 
  summarize(QTD=sum(QTD)) %>% 
  arrange(desc(QTD)) %>% 
  mutate(DATA=Sys.Date()) %>%  as.data.frame()

filewd_emp_resumo <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_mp_emp_resumo","_",format(Sys.Date(),"%d_%m_%y"),".RData")


save(fillrate_mp_emp_resumo,file =filewd_emp_resumo)



#GET SAVED DATA

fillrate_mp <- get(load("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_mp.RData"))


fillrate_mp_resumo <- get(load("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_mp_resumo.RData"))


#JUNTA TODOS OS BLOCOS COM BASE ANTERIOR EM UM UNICO E REMOVE DUPLICADAS
fillrate_mp <- union_all(fillrate_mp,fillrate_mp_emp) %>% arrange(desc(DATA))  %>% distinct() %>% as.data.frame()


# SALVA BASE UNIFICADA
save(fillrate_mp,file = "C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_mp.RData")

# REGISTRA GOOGLE
range_write("1qC12w2k2mZ2RiF_Xsl27C4a3NztilFEgr7qT3sBPYJg",
            data=fillrate_mp,sheet = "PEDIDOS",
            range = "A1",reformat = FALSE)


#ADD BLOCKS
fillrate_mp_resumo <- union_all(fillrate_mp_resumo,fillrate_mp_emp_resumo) %>% distinct() %>% arrange(desc(DATA)) %>%  as.data.frame()

# SAVE BASE
save(fillrate_mp_resumo,file = "C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_mp_resumo.RData")


# REGISTER GOOGLE
range_write("1qC12w2k2mZ2RiF_Xsl27C4a3NztilFEgr7qT3sBPYJg",
            data=fillrate_mp_resumo,sheet = "RESUMOPEDIDOS",
            range = "A1",reformat = FALSE)


#  SAVE CSV FINAL
filewd_fillrate_mp <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_mp.csv")

write.csv2(fillrate_mp, file = filewd_fillrate_mp,row.names=FALSE)

#SAVE CSV FINAL
filewd_fillrate_mp_resumo <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_mp_resumo.csv")

write.csv2(fillrate_mp_resumo, file = filewd_fillrate_mp_resumo,row.names=FALSE)


##  END ORDER DETAIL  ===================================================================================

##  SEND EMAIL  ================

library(gmailr)
library(xlsx)

gm_auth_configure(path = "C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\sendmail.json")


#RESUMO
filewd_fillrate_resumo <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_resumo2","_",format(Sys.Date(),"%d_%m_%y"),".RData")

fillrate_resumo <- get(load(filewd_fillrate_resumo))

#DADOS MP
filewd_emp <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_mp_emp","_",format(Sys.Date(),"%d_%m_%y"),".RData")

fillrate_mp_emp <- get(load(filewd_emp))

## RESUMO MP
filewd_emp_resumo <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_mp_emp_resumo","_",format(Sys.Date(),"%d_%m_%y"),".RData")

fillrate_mp_emp_resumo <- get(load(filewd_emp_resumo))


filewd_emp_mail <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_mp_emp","_",format(Sys.Date(),"%d_%m_%y"),".xlsx")

write.xlsx(fillrate_resumo, file = filewd_emp_mail,row.names=FALSE,sheetName = "RESUMO")
write.xlsx(fillrate_mp_emp, file = filewd_emp_mail,row.names=FALSE,sheetName = "DADOS",append = TRUE)
write.xlsx(fillrate_mp_emp_resumo, file = filewd_emp_mail,row.names=FALSE,sheetName = "DADOS2", append = TRUE)


mymail_fillrate <- gm_mime() %>% 
  gm_to("sandro.jakoska@repro.com.br,,carlos.machado@repro.com.br,debora.rocha@repro.com.br,estagiologistica@repro.com.br,silvano.silva@repro.com.br") %>% 
  gm_from ("comunicacao@repro.com.br") %>%
  gm_subject("RELATORIO FILL RATE") %>%
  gm_text_body("Segue Anexo relatorio.Esse e um email automatico.") %>% 
  gm_attach_file(filewd_emp_mail)

gm_send_message(mymail_fillrate)
