## NIVEL DE SERVICO 
## SEND MAIL
## SANDRO JAKOSKA

## LIBRARIES

library(dplyr)
library(DBI)
library(scales)
library(gmailr)
library(xlsx)

con2 <- dbConnect(odbc::odbc(), "reproreplica")

## MATRIZ

nivelservico1 <- dbGetQuery(con2,"

--pedidos dentro
 
SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO  
, PED.PEDPZENTRE 
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo
WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'

AND PED.EMPCODIGO = 1 
AND PED.TPCODIGO IN (1,6,10,11)
AND NOT EXISTS  (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED  
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) < PED.PEDPZETGSIS

UNION

-- pedidos dentro

SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO
, PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS 
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo
WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'

AND PED.EMPCODIGO = 1 
AND PED.TPCODIGO IN (1,6,10,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T')
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S'
AND PRT.DTINICIO IS NOT NULL AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS
AND COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) < PED.PEDHRETGSIS

UNION

-- pedidos fora

SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO
, PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'F' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

-- periodo

WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'

AND PED.EMPCODIGO = 1 
AND PED.TPCODIGO IN (1,6,10,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED  
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO  
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) > PED.PEDPZETGSIS

UNION

-- pedidos fora

SELECT PED.PEDDTEMIS 
,PED.ID_PEDIDO
, PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'F' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO


-- periodo

WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'

AND PED.EMPCODIGO = 1 AND PED.TPCODIGO IN (1,6,10,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO    
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO  
AND PEDXPED.PEDORIGEMDIV IN ('F','T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO)  
FROM PEDROTEIRO PRT LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO  
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' ) 
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO  
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS
AND CAST(COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME) > CAST(PED.PEDHRETGSIS AS TIME)
ORDER BY 5, 1, 8, 2 ")

## EMPRESA JOINVILLE

nivelservico3 <- dbGetQuery(con2,"

-- dentro

SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO
, PED.PEDPZENTRE 
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

-- periodo
WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'

AND PED.EMPCODIGO = 3 
AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS
 (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO AND ACP.LPCODIGO IN 
 ('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) < PED.PEDPZETGSIS

UNION

SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO
, PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS 
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

-- periodo

WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'

AND PED.EMPCODIGO = 3 
AND PED.TPCODIGO IN (1,11)AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T')
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO AND PRT.PDRCONCLUIDO <> 'S'
AND PRT.DTINICIO IS NOT NULL AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS
AND COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) < PED.PEDHRETGSIS

UNION

-- fora
SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO
, PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'F' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo
WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'

AND PED.EMPCODIGO = 3 AND PED.TPCODIGO IN (1,11)AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO AND 
ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED  
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO  
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S')
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) > PED.PEDPZETGSIS

UNION

-- fora
SELECT PED.PEDDTEMIS 
,PED.ID_PEDIDO
, PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'F' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO


-- periodo
WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'

AND PED.EMPCODIGO = 3 
AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO    
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO  
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') AND TP.TPLAB = 'S') 
AND NOT EXISTS (SELECT (A.ALXCODIGO)  
FROM PEDROTEIRO PRT LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO  
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO  
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS
AND CAST(COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME) > CAST(PED.PEDHRETGSIS AS TIME)
ORDER BY 5, 1, 8, 2 ")


## EMPRESA CRICIUMA

nivelservico4 <- dbGetQuery(con2,"
SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO
, PED.PEDPZENTRE 
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo
WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 4 
AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
 ('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) < PED.PEDPZETGSIS

UNION

--dentro
SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO
, PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS 
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo
WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'



AND PED.EMPCODIGO = 4 
AND PED.TPCODIGO IN (1,11) 
AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T')
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S'
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS
AND COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) < PED.PEDHRETGSIS

UNION

--fora
SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO
, PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'F' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo
WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 4 
AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED  
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO  
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) > PED.PEDPZETGSIS

UNION

--fora
SELECT PED.PEDDTEMIS 
,PED.ID_PEDIDO
, PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'F' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo
WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'

AND PED.EMPCODIGO = 4 
AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO    
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO  
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO)  
FROM PEDROTEIRO PRT LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO  
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO  
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS
AND CAST(COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME) > CAST(PED.PEDHRETGSIS AS TIME)
ORDER BY 5, 1, 8, 2 ")


## EMPRESA CHAPECO

nivelservico5 <- dbGetQuery(con2,"

--dentro
SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO
, PED.PEDPZENTRE 
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo
WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 5 
AND PED.TPCODIGO IN (1,11)AND NOT EXISTS
 (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO AND ACP.LPCODIGO IN 
 ('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') AND TP.TPLAB = 'S')AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL AND A.ALXSOMATEMPOGASTO = 'S' )  AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) < PED.PEDPZETGSIS

UNION

SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO
, PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS 
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo
WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 5 
AND PED.TPCODIGO IN (1,11)AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO AND PEDXPED.PEDORIGEMDIV IN ('F', 'T')
AND TP.TPLAB = 'S')AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO AND A.EMPCODIGO = PRT.EMPCODIGO
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO AND PRT.PDRCONCLUIDO <> 'S'
AND PRT.DTINICIO IS NOT NULL AND A.ALXSOMATEMPOGASTO = 'S' )  AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS
AND COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) < PED.PEDHRETGSIS

UNION

--fora
SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO
, PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'F' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo
WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 5 AND PED.TPCODIGO IN (1,11)AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO AND 
ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED  
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO  AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL AND A.ALXSOMATEMPOGASTO = 'S' )  AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) > PED.PEDPZETGSIS

UNION

SELECT PED.PEDDTEMIS 
,PED.ID_PEDIDO
, PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'F' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo
WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 5 AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO    
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO  
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO)  
FROM PEDROTEIRO PRT LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO  
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO  
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS
AND CAST(COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME) > CAST(PED.PEDHRETGSIS AS TIME)
ORDER BY 5, 1, 8, 2 ")

## EMPRESA BC

nivelservico8 <- dbGetQuery(con2,"

--dentro
SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO
, PED.PEDPZENTRE 
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo
WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 8 
AND PED.TPCODIGO IN ( 1,11)
AND NOT EXISTS
 (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
 AND ACP.LPCODIGO IN 
 ('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED 
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) < PED.PEDPZETGSIS

UNION

--dentro
SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO
, PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS 
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo
WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'

AND PED.EMPCODIGO = 8 
AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T')
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S'
AND PRT.DTINICIO IS NOT NULL AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS
AND COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) < PED.PEDHRETGSIS

UNION

--fora
SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO
, PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'F' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo
WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 8 AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED  
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO  
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) > PED.PEDPZETGSIS

UNION

SELECT PED.PEDDTEMIS 
,PED.ID_PEDIDO
, PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'F' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo
WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 8 
AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO    
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO  
AND PEDXPED.PEDORIGEMDIV IN ('F','T') AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO)  
FROM PEDROTEIRO PRT LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO  
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO  
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS
AND CAST(COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME) > CAST(PED.PEDHRETGSIS AS TIME)
ORDER BY 5, 1, 8, 2 ")

##RESUMO NIVEL DE SERVICO
## MATRIZ
nivelservico_1 <- left_join(nivelservico1 %>% select(TIPO) %>% table() %>% 
                              as.data.frame() %>% `colnames<-`(c('PRAZO','QTD PEDIDOS')),
                            prop.table(table(nivelservico1$TIPO)) %>% as.data.frame() %>% 
                              mutate(Freq=percent(Freq)) %>% 
                              `colnames<-`(c('PRAZO','PERCENTUAL')),by="PRAZO") %>% 
  mutate(EMPRESA="MATRIZ",DATA=Sys.Date())


##JOINVILLE
nivelservico_3 <- left_join(nivelservico3 %>% select(TIPO) %>% table() %>% 
                              as.data.frame() %>% `colnames<-`(c('PRAZO','QTD PEDIDOS')),
                            prop.table(table(nivelservico3$TIPO)) %>% as.data.frame() %>% 
                              mutate(Freq=percent(Freq)) %>% 
                              `colnames<-`(c('PRAZO','PERCENTUAL')),by="PRAZO") %>% 
  mutate(EMPRESA="JOINVILLE",DATA=Sys.Date())


##CRICIUMA
nivelservico_4 <- left_join(nivelservico4 %>% select(TIPO) %>% table() %>% 
                              as.data.frame() %>% `colnames<-`(c('PRAZO','QTD PEDIDOS')),
                            prop.table(table(nivelservico4$TIPO)) %>% as.data.frame() %>% 
                              mutate(Freq=percent(Freq)) %>% 
                              `colnames<-`(c('PRAZO','PERCENTUAL')),by="PRAZO") %>% 
  mutate(EMPRESA="CRICIUMA",DATA=Sys.Date())


##CHAPECO
nivelservico_5 <- left_join(nivelservico5 %>% select(TIPO) %>% table() %>% 
                              as.data.frame() %>% `colnames<-`(c('PRAZO','QTD PEDIDOS')),
                            prop.table(table(nivelservico5$TIPO)) %>% as.data.frame() %>% 
                              mutate(Freq=percent(Freq)) %>% 
                              `colnames<-`(c('PRAZO','PERCENTUAL')),by="PRAZO") %>% 
  mutate(EMPRESA="CHAPECO",DATA=Sys.Date())


## BC
nivelservico_8 <- left_join(nivelservico8 %>% select(TIPO) %>% table() %>% 
                              as.data.frame() %>% `colnames<-`(c('PRAZO','QTD PEDIDOS')),
                            prop.table(table(nivelservico8$TIPO)) %>% as.data.frame() %>% 
                              mutate(Freq=percent(Freq)) %>% 
                              `colnames<-`(c('PRAZO','PERCENTUAL')),by="PRAZO") %>% 
  mutate(EMPRESA="B.CAMBORIU",DATA=Sys.Date())


nivelservico_repro <- union_all(nivelservico_1,nivelservico_3) %>% 
  union_all(.,nivelservico_4) %>%  
  union_all(.,nivelservico_5) %>% 
  union_all(.,nivelservico_8) %>% arrange(desc(DATA)) %>% 
  mutate(DATA=Sys.Date()) %>% 
  distinct() %>% as.data.frame()

filewd_nivelservico_repro <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\LOGISTICA\\BASES\\nivelservico_repro","_",format(Sys.Date(),"%d_%m_%y"),".RData")


save(nivelservico_repro,file =filewd_nivelservico_repro)


## NIVEL DE SERVICO POR LINHAS =========================================================================

## MATRIZ LINHAS

nivelservico_linha_1 <- dbGetQuery(con2,"

--dentro

SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO,
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
 PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo

WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 1 AND PED.TPCODIGO IN (1,6,10,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS 
(SELECT 1 FROM PEDXPED LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T')  
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT  
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO  
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO  WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) < PED.PEDPZETGSIS

UNION

--dentro

SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO,
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo

WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 1 
AND PED.TPCODIGO IN ( 1,6,10,11)
AND NOT EXISTS 
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED 
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS 
AND COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) < PED.PEDHRETGSIS 

UNION 

--fora

SELECT PED.PEDDTEMIS 
,PED.ID_PEDIDO,
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
PED.PEDPZENTRE 
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'F' AS TIPO 
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS 
FROM PEDID PED 
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO 
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT 
AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO 

--periodo

WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 1 AND PED.TPCODIGO IN (1,6,10,11)
AND NOT EXISTS 
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED 
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO  
AND PRT.PDRCONCLUIDO <> 'S'
AND PRT.DTINICIO IS NOT NULL  
AND A.ALXSOMATEMPOGASTO = 'S' ) 
AND AP.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) > PED.PEDPZETGSIS 

UNION 

--fora

SELECT PED.PEDDTEMIS 
,PED.ID_PEDIDO, 
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
PED.PEDPZENTRE 
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE 
, 'F' AS TIPO 
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS 
FROM PEDID PED 
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO 
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo

WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 1 
AND PED.TPCODIGO IN (1,6,10,11)
AND NOT EXISTS  (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128')) 
AND NOT EXISTS (SELECT 1 FROM PEDXPED
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO
AND PEDXPED.PEDORIGEMDIV IN ('F','T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO AND A.EMPCODIGO = PRT.EMPCODIGO
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S'
AND PRT.DTINICIO IS NOT NULL AND A.ALXSOMATEMPOGASTO = 'S')  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS
AND CAST(COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME) > CAST(PED.PEDHRETGSIS AS TIME)
ORDER BY 5, 1, 8, 2")


##JOINVILLE LINHA

nivelservico_linha_3 <- dbGetQuery(con2,"

--dentro 

SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO,
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
 PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo
WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 3 AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS 
(SELECT 1 FROM PEDXPED LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T')  
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT  
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO  
AND PRT.PDRCONCLUIDO <> 'S' AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO  WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) < PED.PEDPZETGSIS

UNION 

--dentro

SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO,
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'



AND PED.EMPCODIGO = 3 AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))AND 
NOT EXISTS (SELECT 1 FROM PEDXPED  
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS 
AND COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) < PED.PEDHRETGSIS 

UNION 

--fora

SELECT PED.PEDDTEMIS 
,PED.ID_PEDIDO,
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
PED.PEDPZENTRE 
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'F' AS TIPO 
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS 
FROM PEDID PED 
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO 
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO 

--periodo

WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 3 AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED 
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) > PED.PEDPZETGSIS 

UNION 

--fora

SELECT PED.PEDDTEMIS 
,PED.ID_PEDIDO, 
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
PED.PEDPZENTRE 
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE 
, 'F' AS TIPO 
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS 
FROM PEDID PED 
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO 
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo

WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 3 
AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128')) 
AND NOT EXISTS (SELECT 1 FROM PEDXPED
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO
AND PEDXPED.PEDORIGEMDIV IN ('F','T') AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO AND A.EMPCODIGO = PRT.EMPCODIGO
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO AND PRT.PDRCONCLUIDO <> 'S'
AND PRT.DTINICIO IS NOT NULL AND A.ALXSOMATEMPOGASTO = 'S' )
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS
AND CAST(COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME) > CAST(PED.PEDHRETGSIS AS TIME)
ORDER BY 5, 1, 8, 2")

##CRICIUMA LINHA

nivelservico_linha_4 <- dbGetQuery(con2,"

--dentro

SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO,
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
 PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO


--periodo

WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'



AND PED.EMPCODIGO = 4 AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS 
(SELECT 1 FROM PEDXPED LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T')  
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT  
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO  
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO  WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) < PED.PEDPZETGSIS

UNION

--dentro

SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO,
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo

WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 4 AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO AND 
ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED  
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO AND PRT.PDRCONCLUIDO <> 'S' AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS 
AND COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) < PED.PEDHRETGSIS 

UNION

--fora

SELECT PED.PEDDTEMIS 
,PED.ID_PEDIDO,
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
PED.PEDPZENTRE 
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'F' AS TIPO 
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS 
FROM PEDID PED 
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO 
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO 

WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 4 
AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED 
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO AND PEDXPED.PEDORIGEMDIV IN ('F','T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) > PED.PEDPZETGSIS 

UNION

--fora

SELECT PED.PEDDTEMIS 
,PED.ID_PEDIDO, 
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
PED.PEDPZENTRE 
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE 
, 'F' AS TIPO 
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS 
FROM PEDID PED 
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO 
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo

WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 4 
AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128')) 
AND NOT EXISTS (SELECT 1 FROM PEDXPED
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S'
AND PRT.DTINICIO IS NOT NULL AND A.ALXSOMATEMPOGASTO = 'S' )
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS
AND CAST(COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME) > CAST(PED.PEDHRETGSIS AS TIME)
ORDER BY 5, 1, 8, 2")


## CHAPECO LINHA

nivelservico_linha_5 <- dbGetQuery(con2,"

--dentro

SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO,
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
 PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

-- periodo
WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 5 
AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T')  
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT  
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO  
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO  WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) < PED.PEDPZETGSIS

UNION

--dentro

SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO,
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo

WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 5 
AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED  
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO AND PRT.PDRCONCLUIDO <> 'S' AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS 
AND COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) < PED.PEDHRETGSIS

UNION

--fora

SELECT PED.PEDDTEMIS 
,PED.ID_PEDIDO,
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
PED.PEDPZENTRE 
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'F' AS TIPO 
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS 
FROM PEDID PED 
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO 
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO 

--periodo

WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'
   

AND PED.EMPCODIGO = 5 
AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED 
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S')  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) > PED.PEDPZETGSIS 

UNION

--fora

SELECT PED.PEDDTEMIS 
,PED.ID_PEDIDO, 
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
PED.PEDPZENTRE 
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE 
, 'F' AS TIPO 
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS 
FROM PEDID PED 
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO 
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo

WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 5 
AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128')) 
AND NOT EXISTS (SELECT 1 FROM PEDXPED
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO
AND PEDXPED.PEDORIGEMDIV IN ('F','T') 
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S'
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS
AND CAST(COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME) > CAST(PED.PEDHRETGSIS AS TIME)
ORDER BY 5, 1, 8, 2")



## BALNEARIO CAMBORIU LINHA

nivelservico_linha_8 <- dbGetQuery(con2,"

--dentro

SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO,
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
 PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo

WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'


AND PED.EMPCODIGO = 8 
AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS 
(SELECT 1 FROM PEDXPED LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F','T')  
AND TP.TPLAB = 'S')
AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT  
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO  
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO  WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) < PED.PEDPZETGSIS

UNION

--dentro

SELECT PED.PEDDTEMIS
,PED.ID_PEDIDO,
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
PED.PEDPZENTRE
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'D' AS TIPO
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS
FROM PEDID PED
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo

WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'



AND PED.EMPCODIGO = 8 AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO 
AND ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED  
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO 
AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') 
AND TP.TPLAB = 'S')AND 
NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO 
AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO 
AND PRT.PDRCONCLUIDO <> 'S' 
AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  
AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS 
AND COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) < PED.PEDHRETGSIS 

UNION

--fora

SELECT PED.PEDDTEMIS 
,PED.ID_PEDIDO,
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
PED.PEDPZENTRE 
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE
, 'F' AS TIPO 
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS 
FROM PEDID PED 
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO 
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO 

--periodo

WHERE 
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'

AND PED.EMPCODIGO = 8 
AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  
(SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO AND 
ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128'))
AND NOT EXISTS (SELECT 1 FROM PEDXPED 
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO 
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO AND PEDXPED.PEDORIGEMDIV IN ('F', 'T') AND TP.TPLAB = 'S')AND 
NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT 
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO AND A.EMPCODIGO = PRT.EMPCODIGO 
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO AND PRT.PDRCONCLUIDO <> 'S' AND PRT.DTINICIO IS NOT NULL 
AND A.ALXSOMATEMPOGASTO = 'S' )  AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) > PED.PEDPZETGSIS 

UNION

--fora

SELECT PED.PEDDTEMIS 
,PED.ID_PEDIDO, 
TPLDESCRICAO LINHA,
PDP.PROCODIGO,
PDPDESCRICAO,
PED.PEDPZENTRE 
, SUBSTR(CAST( COALESCE(PED.PEDHRENTRE, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRENTRE 
, 'F' AS TIPO 
, COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) AS DTENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME),1,5) AS HRENTREGA 
, SUBSTR(CAST( COALESCE(PED.PEDHORAENT, CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHORAENT
, PED.PEDPZETGSIS 
, SUBSTR(CAST( COALESCE(PED.PEDHRETGSIS , CURRENT_TIMESTAMP) AS TIME),1,5) AS PEDHRETGSIS 
FROM PEDID PED 
LEFT JOIN ACOPED AP  ON AP.ID_PEDIDO  = PED.ID_PEDIDO 
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
LEFT JOIN PDPRD PDP ON PDP.ID_PEDIDO = PED.ID_PEDIDO
LEFT JOIN PRODU PRO ON PRO.PROCODIGO = PDP.PROCODIGO
LEFT JOIN TPLENTE TP ON PRO.TPLCODIGO = TP.TPLCODIGO
LEFT JOIN ENDCLI EDC ON EDC.ENDCODIGO = PED.ENDENT AND EDC.CLICODIGO = PED.CLICODIGO
LEFT JOIN CIDADE CID ON CID.CIDCODIGO = EDC.CIDCODIGO

--periodo

WHERE
PED.PEDPZETGSIS >= DATEADD(-7 DAY TO CURRENT_DATE) 
AND 
PED.PEDPZETGSIS < 'TODAY'

AND PED.EMPCODIGO = 8 
AND PED.TPCODIGO IN (1,11)
AND NOT EXISTS  (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO=PED.ID_PEDIDO AND 
ACP.LPCODIGO IN 
('19','50','73','80','8','217','150','151','1827','1810','187','7','172','270','128')) 
AND NOT EXISTS (SELECT 1 FROM PEDXPED
LEFT JOIN TPPEDID TP ON TP.TPCODIGO = PED.TPCODIGO
WHERE PEDXPED.ID_PEDDES = PED.ID_PEDIDO
AND PEDXPED.PEDORIGEMDIV IN ('F','T') AND TP.TPLAB = 'S')AND NOT EXISTS (SELECT (A.ALXCODIGO) FROM PEDROTEIRO PRT
LEFT JOIN ALMOX A ON A.ALXCODIGO = PRT.ALXCODIGO AND A.EMPCODIGO = PRT.EMPCODIGO
WHERE PRT.ID_PEDIDO = PED.ID_PEDIDO AND PRT.PDRCONCLUIDO <> 'S'
AND PRT.DTINICIO IS NOT NULL AND A.ALXSOMATEMPOGASTO = 'S' )  AND AP.APCODIGO  = (SELECT MAX(APCODIGO) FROM ACOPED APO 
LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
WHERE APO.ID_PEDIDO = PED.ID_PEDIDO)
AND COALESCE(PED.PEDDTSAIDA, CURRENT_TIMESTAMP) = PED.PEDPZETGSIS
AND CAST(COALESCE(PED.PEDHRSAIDA, CURRENT_TIMESTAMP) AS TIME) > CAST(PED.PEDHRETGSIS AS TIME)
ORDER BY 5, 1, 8, 2")


## MATRIZ
nivelservico_linha_resumo_1 <-  nivelservico_linha_1 %>% filter(!is.na(LINHA)) %>% group_by(LINHA) %>% 
  summarize(QTD=n_distinct(ID_PEDIDO),QTD_DENTRO=n_distinct(ID_PEDIDO[TIPO=='D']),QTD_FORA=n_distinct(ID_PEDIDO[TIPO=='F'])) %>% 
  mutate(D=percent(QTD_DENTRO/(QTD_DENTRO+QTD_FORA)),F=percent(QTD_FORA/(QTD))) %>% 
  arrange(desc(QTD_FORA)) %>% as.data.frame() %>% 
  mutate(EMPRESA="MATRIZ",DATA=Sys.Date()) %>% .[,-3]


##JOINVILLE
nivelservico_linha_resumo_3<- nivelservico_linha_3 %>% filter(!is.na(LINHA)) %>% group_by(LINHA) %>% 
  summarize(QTD=n_distinct(ID_PEDIDO),QTD_DENTRO=n_distinct(ID_PEDIDO[TIPO=='D']),QTD_FORA=n_distinct(ID_PEDIDO[TIPO=='F'])) %>% 
  mutate(D=percent(QTD_DENTRO/(QTD_DENTRO+QTD_FORA)),F=percent(QTD_FORA/(QTD_DENTRO+QTD_FORA))) %>% 
  arrange(desc(QTD_FORA)) %>% as.data.frame() %>%
  mutate(EMPRESA="JOINVILLE",DATA=Sys.Date()) %>% .[,-3]


##CRICIUMA
nivelservico_linha_resumo_4<- nivelservico_linha_4 %>% filter(!is.na(LINHA)) %>% group_by(LINHA) %>% 
  summarize(QTD=n_distinct(ID_PEDIDO),QTD_DENTRO=n_distinct(ID_PEDIDO[TIPO=='D']),QTD_FORA=n_distinct(ID_PEDIDO[TIPO=='F'])) %>% 
  mutate(D=percent(QTD_DENTRO/(QTD_DENTRO+QTD_FORA)),F=percent(QTD_FORA/(QTD_DENTRO+QTD_FORA))) %>% 
  arrange(desc(QTD_FORA)) %>% as.data.frame() %>% 
  mutate(EMPRESA="CRICIUMA",DATA=Sys.Date())  %>% .[,-3]


##CHAPECO
nivelservico_linha_resumo_5 <- nivelservico_linha_5 %>% filter(!is.na(LINHA)) %>% group_by(LINHA) %>% 
  summarize(QTD=n_distinct(ID_PEDIDO),QTD_DENTRO=n_distinct(ID_PEDIDO[TIPO=='D']),QTD_FORA=n_distinct(ID_PEDIDO[TIPO=='F'])) %>% 
  mutate(D=percent(QTD_DENTRO/(QTD_DENTRO+QTD_FORA)),F=percent(QTD_FORA/(QTD_DENTRO+QTD_FORA))) %>% 
  arrange(desc(QTD_FORA)) %>% as.data.frame() %>% 
  mutate(EMPRESA="CHAPECO",DATA=Sys.Date()) %>% .[,-3]


## BC
nivelservico_linha_resumo_8 <- nivelservico_linha_8 %>% filter(!is.na(LINHA)) %>% group_by(LINHA) %>% 
  summarize(QTD=n_distinct(ID_PEDIDO),QTD_DENTRO=n_distinct(ID_PEDIDO[TIPO=='D']),QTD_FORA=n_distinct(ID_PEDIDO[TIPO=='F'])) %>% 
  mutate(D=percent(QTD_DENTRO/(QTD_DENTRO+QTD_FORA)),F=percent(QTD_FORA/(QTD_DENTRO+QTD_FORA))) %>% 
  arrange(desc(QTD_FORA)) %>% as.data.frame() %>% 
  mutate(EMPRESA="B.CAMBORIU",DATA=Sys.Date()) %>% .[,-3]


nivelservico_repro_linha <- union_all(nivelservico_linha_resumo_1,nivelservico_linha_resumo_3) %>% 
  union_all(.,nivelservico_linha_resumo_4) %>%  
  union_all(.,nivelservico_linha_resumo_5) %>% 
  union_all(.,nivelservico_linha_resumo_8) %>% 
  mutate(DATA=Sys.Date()) %>% distinct() %>% as.data.frame()


filewd_nivelservico_repro_linha <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\LOGISTICA\\BASES\\nivelservico_repro_linha","_",format(Sys.Date(),"%d_%m_%y"),".RData")


save(nivelservico_repro_linha,file =filewd_nivelservico_repro_linha)



## SEND MAIL =========================================================================


gm_auth_configure(path = "C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\LOGISTICA\\sendmail.json")


#RESUMO
filewd_nivelservico_repro <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\LOGISTICA\\BASES\\nivelservico_repro","_",format(Sys.Date(),"%d_%m_%y"),".RData")

nivelservico_repro2 <- get(load(filewd_nivelservico_repro))

#DADOS
filewd_nivelservico_repro_linha <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\LOGISTICA\\BASES\\nivelservico_repro_linha","_",format(Sys.Date(),"%d_%m_%y"),".RData")

nivelservico_repro_linha2 <- get(load(filewd_nivelservico_repro_linha))


filewd_nivelservico <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\LOGISTICA\\BASES\\nivelservico","_",format(Sys.Date(),"%d_%m_%y"),".xlsx")

write.xlsx(nivelservico_repro2, file = filewd_nivelservico,row.names=FALSE,sheetName = "RESUMO")
write.xlsx(nivelservico_repro_linha2, file = filewd_nivelservico,row.names=FALSE,sheetName = "DADOS",append = TRUE)


mymail_nivelservico <- gm_mime() %>% 
  gm_to("sandro.jakoska@repro.com.br") %>% 
  gm_from ("comunicacao@repro.com.br") %>%
  gm_subject("RELATORIO NIVEL DE SERVIÇO") %>%
  gm_text_body("Segue Anexo relatorio.Esse e um email automatico.") %>% 
  gm_attach_file(filewd_nivelservico)

gm_send_message(mymail_nivelservico)



