### FILL RATE REPRO
### LENTES ACABADAS
## SANDRO JAKOSKA 2022

## LIBRARIES

library(tidyverse)
library(reshape2)
library(DBI)
library(googlesheets4)
con2 <- dbConnect(odbc::odbc(), "reproreplica")


### TOTAL PEDIDOS

tot_ped_LA <- dbGetQuery(con2,"
WITH  
PED_DATES AS (SELECT ID_PEDIDO FROM PEDID WHERE 
/* DATES */ 

PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022'),


RESULT1 AS (SELECT P.ID_PEDIDO,TPCODIGO,AP.APCODIGO FROM
PEDID P
INNER JOIN PED_DATES PDT ON P.ID_PEDIDO=PDT.ID_PEDIDO

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN PED_DATES PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2 AND PROSITUACAO='A') PR ON PD.PROCODIGO=PR.PROCODIGO) PDP ON PDP.ID_PEDIDO=P.ID_PEDIDO   

LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO

WHERE 

P.EMPCODIGO=1
AND TPCODIGO IN (1,2,3,6,7,12,14)
AND PEDSITPED IN ('A','F') ),

RESULT3 AS (SELECT P.ID_PEDIDO,TPCODIGO,AP.APCODIGO FROM
PEDID P

INNER JOIN PED_DATES PDT ON P.ID_PEDIDO=PDT.ID_PEDIDO

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN PED_DATES PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2 AND PROSITUACAO='A') PR ON PD.PROCODIGO=PR.PROCODIGO)PDP ON PDP.ID_PEDIDO=P.ID_PEDIDO

LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO


WHERE 


P.EMPCODIGO=3
AND TPCODIGO IN (1,3)
AND PEDSITPED IN ('A','F') ),

RESULT4 AS (SELECT P.ID_PEDIDO,TPCODIGO,AP.APCODIGO FROM
PEDID P

INNER JOIN PED_DATES PDT ON P.ID_PEDIDO=PDT.ID_PEDIDO

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN PED_DATES PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2 AND PROSITUACAO='A') PR ON PD.PROCODIGO=PR.PROCODIGO)PDP ON PDP.ID_PEDIDO=P.ID_PEDIDO

LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO


WHERE 


P.EMPCODIGO=4
AND TPCODIGO IN (1,3)
AND PEDSITPED IN ('A','F') ),

RESULT5 AS (SELECT P.ID_PEDIDO,TPCODIGO,AP.APCODIGO FROM
PEDID P

INNER JOIN PED_DATES PDT ON P.ID_PEDIDO=PDT.ID_PEDIDO

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN PED_DATES PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2 AND PROSITUACAO='A') PR ON PD.PROCODIGO=PR.PROCODIGO)PDP ON PDP.ID_PEDIDO=P.ID_PEDIDO 

LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO

WHERE 

P.EMPCODIGO=5
AND TPCODIGO IN (1,3)
AND PEDSITPED IN ('A','F') ),

RESULT8 AS (SELECT P.ID_PEDIDO,TPCODIGO,AP.APCODIGO FROM
PEDID P

INNER JOIN PED_DATES PDT ON P.ID_PEDIDO=PDT.ID_PEDIDO

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN PED_DATES PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2 AND PROSITUACAO='A') PR ON PD.PROCODIGO=PR.PROCODIGO)PDP ON PDP.ID_PEDIDO=P.ID_PEDIDO 

LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO

WHERE 

P.EMPCODIGO=8
AND TPCODIGO IN (1,3,9)
AND PEDSITPED IN ('A','F')),

RESULT9 AS (SELECT P.ID_PEDIDO,TPCODIGO,AP.APCODIGO FROM
PEDID P

INNER JOIN PED_DATES PDT ON P.ID_PEDIDO=PDT.ID_PEDIDO

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN PED_DATES PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2 AND PROSITUACAO='A') PR ON PD.PROCODIGO=PR.PROCODIGO)PDP ON PDP.ID_PEDIDO=P.ID_PEDIDO   
  

LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO

WHERE 

P.EMPCODIGO=1
AND TPCODIGO IN (10,11)
AND PEDSITPED IN ('A','F'))

 /* SELECT BY EMP */ 
 
 SELECT 'MATRIZ' EMPRESA,TPCODIGO TIPO,'TOTAL PEDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT1 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
      GROUP BY 1,2,3 UNION
    
      
    SELECT 'JOINVILLE' EMPRESA,TPCODIGO TIPO,'TOTAL PEDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT3 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
      GROUP BY 1,2,3 UNION
      
     SELECT 'CRICIUMA' EMPRESA,TPCODIGO TIPO,'TOTAL PEDIDOS' INDICADOR, COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT4 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
      GROUP BY 1,2,3 UNION
      
      SELECT 'CHAPECO' EMPRESA,TPCODIGO TIPO,'TOTAL PEDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT5 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
      GROUP BY 1,2,3 UNION
      
      SELECT 'BALNEARIO C' EMPRESA,TPCODIGO TIPO,'TOTAL PEDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT8 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
      GROUP BY 1,2,3 UNION
      
      SELECT 'MATRIZ' EMPRESA,TPCODIGO TIPO,'TOTAL PEDIDOS CONTROL' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT9 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
      GROUP BY 1,2,3
") 


tot_ped_natd_LA <- dbGetQuery(con2,"
WITH PED_DATES AS (SELECT ID_PEDIDO FROM PEDID WHERE 
/* DATES */ 

PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022'),
--------------------------------------)

RESULT1 AS (SELECT P.ID_PEDIDO,
                    TPCODIGO,
                     AP.APCODIGO,
                      LP.LPCODIGO FROM
PEDID P

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN PED_DATES PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2 AND PROSITUACAO='A') PR ON PD.PROCODIGO=PR.PROCODIGO) PDP ON PDP.ID_PEDIDO=P.ID_PEDIDO   

LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 

P.EMPCODIGO=1
AND TPCODIGO IN (1,2,3,6,7,12,14)
AND PEDSITPED IN ('A','F') ),


RESULT3 AS (SELECT P.ID_PEDIDO,
                    TPCODIGO,
                      AP.APCODIGO, 
                       LP.LPCODIGO FROM
PEDID P

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN PED_DATES PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2 AND PROSITUACAO='A') PR ON PD.PROCODIGO=PR.PROCODIGO) PDP ON PDP.ID_PEDIDO=P.ID_PEDIDO   
                  
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 

P.EMPCODIGO=3
AND TPCODIGO IN (1,3)
AND PEDSITPED IN ('A','F') ),

RESULT4 AS (SELECT P.ID_PEDIDO,
                    TPCODIGO,
                     AP.APCODIGO,
                      LP.LPCODIGO FROM
PEDID P

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN PED_DATES PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2 AND PROSITUACAO='A') PR ON PD.PROCODIGO=PR.PROCODIGO) PDP ON PDP.ID_PEDIDO=P.ID_PEDIDO   
                  
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 

P.EMPCODIGO=4
AND TPCODIGO IN (1,3)
AND PEDSITPED IN ('A','F') ),

RESULT5 AS (SELECT P.ID_PEDIDO,
                    TPCODIGO,
                      AP.APCODIGO,
                       LP.LPCODIGO FROM
PEDID P

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN PED_DATES PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2 AND PROSITUACAO='A') PR ON PD.PROCODIGO=PR.PROCODIGO) PDP ON PDP.ID_PEDIDO=P.ID_PEDIDO   

LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 
P.EMPCODIGO=5
AND TPCODIGO IN (1,3)
AND PEDSITPED IN ('A','F') ),

RESULT8 AS (SELECT P.ID_PEDIDO,
                    TPCODIGO,
                     AP.APCODIGO,
                      LP.LPCODIGO FROM
PEDID P

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN PED_DATES PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2 AND PROSITUACAO='A') PR ON PD.PROCODIGO=PR.PROCODIGO) PDP ON PDP.ID_PEDIDO=P.ID_PEDIDO   

LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 

P.EMPCODIGO=8
AND TPCODIGO IN (1,3,9)
AND PEDSITPED IN ('A','F') ),

RESULT9 AS (SELECT P.ID_PEDIDO,
                    TPCODIGO,
                     AP.APCODIGO,
                      LP.LPCODIGO FROM
PEDID P

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN PED_DATES PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2 AND PROSITUACAO='A') PR ON PD.PROCODIGO=PR.PROCODIGO) PDP ON PDP.ID_PEDIDO=P.ID_PEDIDO   
                  
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 

P.EMPCODIGO=1
AND TPCODIGO IN (10,11)
AND PEDSITPED IN ('A','F') )
 
 SELECT 'MATRIZ' EMPRESA, 
          TPCODIGO TIPO,
           'PEDIDOS NAO ATENDIDOS' INDICADOR,
             COUNT(DISTINCT R.ID_PEDIDO) TOTAL
             
   FROM RESULT1 R
   WHERE
      R.ID_PEDIDO > 0
       AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
        LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
         WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
          AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
           AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
            AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
             GROUP BY 1,2,3 UNION
      
      
 SELECT 'JOINVILLE' EMPRESA,
          TPCODIGO TIPO,
           'PEDIDOS NAO ATENDIDOS' INDICADOR,
             COUNT(DISTINCT R.ID_PEDIDO) TOTAL
             
   FROM RESULT3 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
      GROUP BY 1,2,3 UNION
      
     SELECT 'CRICIUMA' EMPRESA, 
              TPCODIGO TIPO,
               'PEDIDOS NAO ATENDIDOS' INDICADOR,
                 COUNT(DISTINCT R.ID_PEDIDO) TOTAL
                 
   FROM RESULT4 R
   WHERE
   
      R.ID_PEDIDO > 0
       AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
        LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
         WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
          AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
           AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
            AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
       GROUP BY 1,2,3 UNION
      
      SELECT 'CHAPECO' EMPRESA, 
               TPCODIGO TIPO,
                'PEDIDOS NAO ATENDIDOS' INDICADOR,
                  COUNT(DISTINCT R.ID_PEDIDO) TOTAL
                  
   FROM RESULT5 R
   WHERE
   
      R.ID_PEDIDO > 0
       AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
        LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
         WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
          AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
           AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
            AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
             GROUP BY 1,2,3 UNION
      
      SELECT 'BALNEARIO C' EMPRESA,
               TPCODIGO TIPO,
               'PEDIDOS NAO ATENDIDOS' INDICADOR,
                 COUNT(DISTINCT R.ID_PEDIDO) TOTAL
                 
   FROM RESULT8 R
    WHERE
    
      R.ID_PEDIDO > 0
       AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
        LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
         WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
          AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
           AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
            AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
             GROUP BY 1,2,3 UNION
      
      SELECT 'MATRIZ' EMPRESA,
               TPCODIGO TIPO,
                'PEDIDOS CONTROL NAO ATENDIDOS' INDICADOR,
                  COUNT(DISTINCT R.ID_PEDIDO) TOTAL
                  
   FROM RESULT9 R
    WHERE
   
      R.ID_PEDIDO > 0
       AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
        LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
         WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
          AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
           AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
            AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
             GROUP BY 1,2,3
")


ped_control_LA <- dbGetQuery(con2,"
  EXECUTE BLOCK RETURNS (EMPRESA VARCHAR(30),TIPO VARCHAR(30),INDICADOR VARCHAR(30),TOTAL DECIMAL(15,2))
  
  AS DECLARE VARIABLE CLIENTE INT;
  
  BEGIN
  FOR
  
  SELECT DISTINCT CLICODIGO
                   FROM CLIEN
                    WHERE CLICODIGO IN (495,1065,81,5)

                     INTO :CLIENTE
                      DO
                       BEGIN
                        FOR
                        
  
                         SELECT 
                           CASE 
                            WHEN CLICODIGO=495 THEN 'JOINVILLE'
                             WHEN CLICODIGO=1065 THEN 'CRICIUMA'
                              WHEN CLICODIGO=81 THEN 'CHAPECO'
                               WHEN CLICODIGO=5 THEN 'BALNEARIO C'
                                END FILIAL,
                                 TPCODIGO,
                                  COUNT (DISTINCT (P.ID_PEDIDO)) TOTAL,'CONTROL' INDICADOR
                                   FROM PEDID P
                                   
                                   INNER JOIN (SELECT ID_PEDIDO FROM PEDID WHERE 
/* DATES */ 

PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022') PDT ON P.ID_PEDIDO=PDT.ID_PEDIDO
                                   
                                    /* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN (SELECT ID_PEDIDO FROM PEDID WHERE 
/* DATES */ 

PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022') PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2) 
                  PR ON PR.PROCODIGO=PD.PROCODIGO) PRD ON P.ID_PEDIDO=PRD.ID_PEDIDO 
                  
                                    WHERE P.PEDSITPED IN ('A','F')
                                     AND P.CLICODIGO = :CLIENTE AND P.TPCODIGO IN ('10','11')  


AND EXISTS (SELECT 1 FROM PEDROTEIRO PR1 WHERE PR1.ALXCODIGO = 1 AND PR1.ID_PEDIDO = P.ID_PEDIDO)
AND NOT EXISTS (SELECT 1 FROM PEDROTEIRO PR2 WHERE PR2.ALXCODIGO IN ('15','16','10','9','38','40','6') 
AND PR2.ID_PEDIDO = P.ID_PEDIDO) GROUP BY 1,2
  
  INTO :EMPRESA,:TIPO, :TOTAL,:INDICADOR
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END 
  
  ")

ped_quebras_LA <- dbGetQuery(con2,"

WITH  
PED_DATES AS (SELECT ID_PEDIDO FROM PEDID WHERE 
/* DATES */ 

PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022')


SELECT 
      CASE 
       WHEN EMPCODIGO=1 THEN 'MATRIZ' 
        WHEN EMPCODIGO=3 THEN 'JOINVILLE'
         WHEN EMPCODIGO=4 THEN 'CRICIUMA'
          WHEN EMPCODIGO=5  THEN 'CHAPECO'
           WHEN EMPCODIGO=8  THEN 'B.CAMBORIU' 
            ELSE '' END EMPRESA,
      
        TPCODIGO TIPO,
         'QUEBRAS' INDICADOR,
           COUNT(P.ID_PEDIDO) TOTAL
            FROM PEDID P
            
            INNER JOIN PED_DATES PDT ON P.ID_PEDIDO=PDT.ID_PEDIDO
             
            /* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN PED_DATES PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2) 
                  PR ON PR.PROCODIGO=PD.PROCODIGO) PRD ON P.ID_PEDIDO=PRD.ID_PEDIDO 
                  
             WHERE FISCODIGO1='5.927'
              AND CLICODIGO=579

               GROUP BY 1,2,3
--------------------------------------")


## RESUMO PEDIDOS POR TIPO

fillrate_resumo_1_LA <- rbind(tot_ped_LA,tot_ped_natd_LA,ped_control_LA,ped_quebras_LA) %>% 
  mutate(TIPO=as.numeric(TIPO))

fillrate_resumo_2_LA <- fillrate_resumo_1_LA %>% 
  dcast(EMPRESA + INDICADOR ~ TIPO,value.var = "TOTAL") %>% 
  arrange(desc(EMPRESA)) %>% 
  as.data.frame()  %>% 
  rowwise() %>% 
  mutate(TOTAL= rowSums(across(where(is.numeric)),na.rm = TRUE)) %>% 
  mutate(DATA='23.01.2022 - 29.01.2022')




View(fillrate_resumo_2_LA)

## SAVE SUMMARY 

filewd_fillrate_resumo_2_LA <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_resumo_2_LA","_",format(Sys.Date(),"%d_%m_%y"),".RData")

save(fillrate_resumo_2_LA,file =filewd_fillrate_resumo_2_LA)



## CALCULO FILL RATE =================================================================


## CALCULO FILIAIS 

fillrate_calc_filiais_LA <- fillrate_resumo_1_LA %>% 
  filter(!str_detect(EMPRESA,"MATRIZ")) %>% 
  group_by(EMPRESA) %>% 
  mutate(INDICADOR=trimws(INDICADOR)) %>% 
  summarize(VALOR=(1-((sum(TOTAL[INDICADOR=='CONTROL'])+sum(TOTAL[INDICADOR=='PEDIDOS NAO ATENDIDOS']))/
                        sum(TOTAL[INDICADOR=='TOTAL PEDIDOS'])))*100) %>%
  mutate(VALOR=round(VALOR,2)) %>% mutate(INDICADOR="FILL RATE: CONTROL + NAO ATENDIDOS x TOTAL PEDIDOS") %>% 
  mutate(DATA='23.01.2022 - 29.01.2022') %>% as.data.frame() %>% .[,c(1,3,2,4)] 


## CALCULO MATRIZ

fillrate_calc_matriz_1_LA <- fillrate_resumo_1_LA %>%  
  filter(str_detect(EMPRESA,"MATRIZ"))%>% 
  group_by(EMPRESA) %>% 
  mutate(INDICADOR=trimws(INDICADOR)) %>% 
  summarize(VALOR=(1-((sum(TOTAL[INDICADOR=='PEDIDOS NAO ATENDIDOS']))/sum(TOTAL[INDICADOR=='TOTAL PEDIDOS'])))*100) %>%
  mutate(VALOR=round(VALOR,2)) %>% mutate(INDICADOR="FILL RATE: NAO ATENDIDOS x TOTAL") %>% 
  mutate(DATA='23.01.2022 - 29.01.2022') %>% as.data.frame() %>% .[,c(1,3,2,4)] 

fillrate_calc_matriz_2_LA <- fillrate_resumo_1_LA %>%  
  mutate(INDICADOR=trimws(INDICADOR)) %>% 
  filter(str_detect(EMPRESA,"MATRIZ"))%>% 
  group_by(EMPRESA) %>%
  summarize(VALOR=(1-((sum(TOTAL[INDICADOR=='PEDIDOS CONTROL NAO ATENDIDOS']))/sum(TOTAL[INDICADOR=='TOTAL PEDIDOS CONTROL'])))*100) %>%
  mutate(VALOR=round(VALOR,2)) %>% mutate(INDICADOR="FILL RATE: CONTROL NAO ATENDIDOS x CONTROL TOTAL") %>% 
  mutate(DATA='23.01.2022 - 29.01.2022') %>% as.data.frame() %>% .[,c(1,3,2,4)] 

fillrate_calc_matriz_3_LA <- fillrate_resumo_1_LA %>%  
  mutate(INDICADOR=trimws(INDICADOR)) %>% 
  filter(str_detect(EMPRESA,"MATRIZ"))%>% 
  group_by(EMPRESA) %>%
  summarize(VALOR=(1-((sum(TOTAL[INDICADOR=='PEDIDOS CONTROL NAO ATENDIDOS']))/sum(TOTAL[INDICADOR=='TOTAL PEDIDOS'])))*100) %>%
  mutate(VALOR=round(VALOR,2)) %>% mutate(INDICADOR="FILL RATE: CONTROL NAO ATENDIDOS x TOTAL PEDIDOS") %>% 
  mutate(DATA='23.01.2022 - 29.01.2022') %>% as.data.frame() %>% .[,c(1,3,2,4)] 


fillrate_calc_LA <- union_all(fillrate_calc_filiais_LA,fillrate_calc_matriz_1_LA) %>% 
  union_all(.,fillrate_calc_matriz_2_LA) %>% 
  union_all(.,fillrate_calc_matriz_3_LA) %>% rename(TOTAL=VALOR)



## SAVE CALC SUMMARY 

filewd_fillrate_calc_LA<-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_calc_LA","_",format(Sys.Date(),"%d_%m_%y"),".RData")

save(fillrate_calc_LA,file =filewd_fillrate_calc_LA)


## START ORDER DETAILS =========================================================================================

# MATRIZ

fillrate_mp_matriz_LA <- dbGetQuery(con2,"
  EXECUTE BLOCK RETURNS (
                        EMPRESA VARCHAR(30),
                         INDICADOR VARCHAR(30),
                          PEDIDO INT,
                           EMISSAO DATE,   
                            MATERIAL VARCHAR(100),
                             NOME VARCHAR(100),
                              UN VARCHAR(30), 
                               SEQ VARCHAR(30),
                                CHAVE VARCHAR(30),
                                 DESCRICAO_CHAVE VARCHAR(100),
                                  QTD DECIMAL(15,2))
  
  AS DECLARE VARIABLE ID_PEDIDO INT;
  
  BEGIN
  FOR
  
  /* FILTRO PEDIDOS NAO ATENDIDOS MATRIZ */ 
  
WITH 
RESULT1 AS (SELECT DISTINCT P.ID_PEDIDO,PEDDTEMIS,AP.APCODIGO,LP.LPCODIGO FROM
PEDID P

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN (SELECT ID_PEDIDO FROM PEDID WHERE PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022') PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2) 
                  PR ON PR.PROCODIGO=PD.PROCODIGO) PRD ON P.ID_PEDIDO=PRD.ID_PEDIDO 
                  
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE

/* DATES */ 

PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022'
--------------------------------------

AND P.EMPCODIGO=1
AND TPCODIGO IN (1,2,3,6,7,12,14)
AND PEDSITPED IN ('A','F'))
 
 SELECT DISTINCT R.ID_PEDIDO
   FROM RESULT1 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )

  INTO :ID_PEDIDO 
  DO
  BEGIN
  FOR

  /* FILTRO PEDIDOS NAO ATENDIDOS MATRIZ */ 
  
  WITH PED AS (SELECT ID_PEDIDO,PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO),
  
      PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM PRODU WHERE PROSITUACAO='A' AND PROTIPO NOT IN ('T','M','S','C'))

  
  SELECT
   'MATRIZ' EMPRESA,
    'PEDIDOS NAO ATENDIDOS' INDICADOR,
      ID_PEDIDO,
       (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
        RP.PROCODIGO MATERIAL , 
         RP.RQPDESCRICAO NOME , 
          PD.PROUN UN , 
           RQPSEQ,
            PD.PROCODIGO2 CHAVE,
             (SELECT DISTINCT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PD.PROCODIGO2) DESCRICAO_CHAVE,
              RP.RQPQTDADE QTD    
               FROM PEDCELPDCAO PCP
              LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
               LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
                LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
                 INNER JOIN (SELECT PROCODIGO,PROCODIGO2,PRODESCRICAO,PROUN FROM PRODU WHERE PROTIPO NOT IN ('T','S')) PD ON PD.PROCODIGO = RP.PROCODIGO

WHERE
PCP.ID_PEDIDO = :ID_PEDIDO AND
RP.PROCODIGO IS NOT NULL UNION

SELECT
  'MATRIZ' EMPRESA,
   'PEDIDOS NAO ATENDIDOS' INDICADOR,
     PRD.ID_PEDIDO,
      (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
       PRD.PROCODIGO MATERIAL , 
        PDPDESCRICAO NOME , 
         (SELECT DISTINCT PROUN FROM PRODU WHERE PROCODIGO=CHAVE ) UN,
          '' RQPSEQ,
           CHAVE CHAVE,
            (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE ) DESCRICAO_CHAVE,
              PRD.PDPQTDADE QTD    
               FROM PDPRD PRD
      INNER JOIN PED ON PRD.ID_PEDIDO=PED.ID_PEDIDO
      INNER JOIN PROD P ON PRD.PROCODIGO=P.PROCODIGO
  
  INTO :EMPRESA,:INDICADOR,:PEDIDO,:EMISSAO, :MATERIAL,:NOME, :UN, :SEQ,:CHAVE, :DESCRICAO_CHAVE,:QTD
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END 
  
  ")

#JOINVILLE
fillrate_mp_joinville_LA  <- dbGetQuery(con2,"
  EXECUTE BLOCK RETURNS ( 
                      EMPRESA VARCHAR(30),
                       INDICADOR VARCHAR(30), 
                        PEDIDO INT,
                         EMISSAO DATE,   
                          MATERIAL VARCHAR(100),
                           NOME VARCHAR(100),
                            UN VARCHAR(30), 
                             SEQ VARCHAR(30),
                               CHAVE VARCHAR(30),
                                DESCRICAO_CHAVE VARCHAR(100),
                                 QTD DECIMAL(15,2))
  
  AS DECLARE VARIABLE ID_PEDIDO INT;
  
  BEGIN
  FOR
  

 /* FILTRO PEDIDOS NAO ATENDIDOS JOINVILLE */ 
  
WITH 
RESULT3 AS (SELECT DISTINCT P.ID_PEDIDO,PEDDTEMIS,AP.APCODIGO,LP.LPCODIGO FROM
PEDID P

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN(SELECT ID_PEDIDO FROM PEDID WHERE PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022') PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2) 
                  PR ON PR.PROCODIGO=PD.PROCODIGO) PRD ON P.ID_PEDIDO=PRD.ID_PEDIDO 
                  
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 


/* DATES */ 

PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022'
--------------------------------------

AND
P.EMPCODIGO=3
AND TPCODIGO IN (1,3)
AND PEDSITPED IN ('A','F'))
 
 SELECT DISTINCT R.ID_PEDIDO
   FROM RESULT3 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )

  INTO :ID_PEDIDO 
  DO
  BEGIN
  FOR
  
 /* LENTES COM PRODUCAO */ 
  
  WITH PED AS (SELECT ID_PEDIDO,PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO),
  
  PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM PRODU WHERE PROSITUACAO='A' AND PROTIPO NOT IN ('T','M','S','C'))

  
  SELECT
  'JOINVILLE' EMPRESA,
  'PEDIDOS NAO ATENDIDOS' INDICADOR,
   ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   RP.PROCODIGO MATERIAL , 
    RP.RQPDESCRICAO NOME , 
     PD.PROUN UN,
      RQPSEQ,
      PD.PROCODIGO2 CHAVE,
      (SELECT DISTINCT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PD.PROCODIGO2) DESCRICAO_CHAVE,
      RP.RQPQTDADE QTD    
      FROM PEDCELPDCAO PCP
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO,PROCODIGO2,PRODESCRICAO,PROUN FROM PRODU WHERE PROTIPO NOT IN ('T','S')) PD ON PD.PROCODIGO = RP.PROCODIGO

WHERE
PCP.ID_PEDIDO = :ID_PEDIDO AND
RP.PROCODIGO IS NOT NULL UNION

/* SELECIONA LENTES ACABADAS */

SELECT
  'JOINVILLE' EMPRESA,
  'PEDIDOS NAO ATENDIDOS' INDICADOR,
   PRD.ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   PRD.PROCODIGO MATERIAL , 
    PDPDESCRICAO NOME , 
      (SELECT DISTINCT PROUN FROM PRODU WHERE PROCODIGO=CHAVE ) UN,
      '' RQPSEQ,
      CHAVE CHAVE,
      (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE ) DESCRICAO_CHAVE,
      PRD.PDPQTDADE QTD    
      FROM PDPRD PRD
      INNER JOIN PED ON PRD.ID_PEDIDO=PED.ID_PEDIDO
      INNER JOIN PROD P ON PRD.PROCODIGO=P.PROCODIGO
  
  INTO :EMPRESA,:INDICADOR,:PEDIDO,:EMISSAO, :MATERIAL,:NOME, :UN, :SEQ,:CHAVE, :DESCRICAO_CHAVE,:QTD
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END 
  
  ")

#CRICIUMA
fillrate_mp_criciuma_LA  <- dbGetQuery(con2,"
 EXECUTE BLOCK RETURNS ( 
                      EMPRESA VARCHAR(30), 
                       INDICADOR VARCHAR(30),
                        PEDIDO INT,
                          EMISSAO DATE,   
                            MATERIAL VARCHAR(100),
                             NOME VARCHAR(100),
                              UN VARCHAR(30), 
                               SEQ VARCHAR(30),
                                CHAVE VARCHAR(30),
                                 DESCRICAO_CHAVE VARCHAR(100),
                                  QTD DECIMAL(15,2))
  
  AS DECLARE VARIABLE ID_PEDIDO INT;
  
  BEGIN
  FOR
  
    /* FILTRO PEDIDOS NAO ATENDIDOS CRICIUMA */
  
WITH 
RESULT1 AS (SELECT DISTINCT P.ID_PEDIDO,PEDDTEMIS,AP.APCODIGO,LP.LPCODIGO FROM
PEDID P

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
                INNER JOIN (SELECT ID_PEDIDO FROM PEDID WHERE PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022') PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                 INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2) 
                  PR ON PR.PROCODIGO=PD.PROCODIGO) PRD ON P.ID_PEDIDO=PRD.ID_PEDIDO 
                  
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 

/* DATES */ 

PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022'
--------------------------------------


AND
P.EMPCODIGO=4
AND TPCODIGO IN (1,2,3,6,7,12,14)
AND PEDSITPED IN ('A','F'))
 
 SELECT DISTINCT R.ID_PEDIDO
   FROM RESULT1 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )

  INTO :ID_PEDIDO 
  DO
  BEGIN
  FOR
  
   /* LENTES COM PRODUCAO */ 
  
  WITH PED AS (SELECT ID_PEDIDO,PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO),
  
  PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM 
  PRODU WHERE PROSITUACAO='A' AND PROTIPO NOT IN ('T','M','S','C'))

  
  SELECT
   'CRICIUMA' EMPRESA,
   'PEDIDOS NAO ATENDIDOS' INDICADOR,
   ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   RP.PROCODIGO MATERIAL , 
    RP.RQPDESCRICAO NOME , 
     PD.PROUN UN , 
      RQPSEQ,
      PD.PROCODIGO2 CHAVE,
      (SELECT DISTINCT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PD.PROCODIGO2) DESCRICAO_CHAVE,
      RP.RQPQTDADE QTD    
      FROM PEDCELPDCAO PCP
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO,PROCODIGO2,PRODESCRICAO,PROUN FROM PRODU WHERE PROTIPO NOT IN ('T','S')) PD ON PD.PROCODIGO = RP.PROCODIGO

WHERE
PCP.ID_PEDIDO = :ID_PEDIDO AND
RP.PROCODIGO IS NOT NULL UNION

/* SELECIONA LENTES ACABADAS */

SELECT
  'CRICIUMA' EMPRESA,
  'PEDIDOS NAO ATENDIDOS' INDICADOR,
   PRD.ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   PRD.PROCODIGO MATERIAL , 
    PDPDESCRICAO NOME , 
      (SELECT DISTINCT PROUN FROM PRODU WHERE PROCODIGO=CHAVE ) UN,
      '' RQPSEQ,
      CHAVE CHAVE,
      (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE ) DESCRICAO_CHAVE,
      PRD.PDPQTDADE QTD    
      FROM PDPRD PRD
      INNER JOIN PED ON PRD.ID_PEDIDO=PED.ID_PEDIDO
      INNER JOIN PROD P ON PRD.PROCODIGO=P.PROCODIGO
  
  INTO :EMPRESA,:INDICADOR,:PEDIDO,:EMISSAO, :MATERIAL,:NOME, :UN,:SEQ,:CHAVE, :DESCRICAO_CHAVE,:QTD
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END 
  
  ")

#CHAPECO
fillrate_mp_chapeco_LA  <- dbGetQuery(con2,"
 EXECUTE BLOCK RETURNS ( 
                      EMPRESA VARCHAR(30),
                       INDICADOR VARCHAR(30), 
                        PEDIDO INT,
                          EMISSAO DATE,   
                           MATERIAL VARCHAR(100),
                             NOME VARCHAR(100),
                              UN VARCHAR(30), 
                               SEQ VARCHAR(30),
                                CHAVE VARCHAR(30),
                                 DESCRICAO_CHAVE VARCHAR(100),
                                  QTD DECIMAL(15,2))
  
  AS DECLARE VARIABLE ID_PEDIDO INT;
  
  BEGIN
  FOR
  
    /* FILTRO PEDIDOS NAO ATENDIDOS CHAPECO */
  
WITH 
RESULT1 AS (SELECT DISTINCT P.ID_PEDIDO,PEDDTEMIS,AP.APCODIGO,LP.LPCODIGO FROM
PEDID P

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
                INNER JOIN (SELECT ID_PEDIDO FROM PEDID WHERE PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022') PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                 INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2) 
                  PR ON PR.PROCODIGO=PD.PROCODIGO) PRD ON P.ID_PEDIDO=PRD.ID_PEDIDO 

LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 

/* DATES */ 

PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022'
--------------------------------------

AND
P.EMPCODIGO=5
AND TPCODIGO IN (1,2,3,6,7,12,14)
AND PEDSITPED IN ('A','F'))
 
 SELECT DISTINCT R.ID_PEDIDO
   FROM RESULT1 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )

  INTO :ID_PEDIDO 
  DO
  BEGIN
  FOR
  
   /* LENTES COM PRODUCAO */ 
  
  WITH PED AS (SELECT ID_PEDIDO,PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO),
  
  PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM 
  PRODU WHERE PROSITUACAO='A' AND PROTIPO NOT IN ('T','M','S','C'))
  
  SELECT
   'CHAPECO' EMPRESA,
   'PEDIDOS NAO ATENDIDOS' INDICADOR,
   ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO,
   RP.PROCODIGO MATERIAL , 
    RP.RQPDESCRICAO NOME , 
     PD.PROUN UN , 
      RQPSEQ,
      PD.PROCODIGO2 CHAVE,
      (SELECT DISTINCT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PD.PROCODIGO2) DESCRICAO_CHAVE,
      RP.RQPQTDADE QTD    
      FROM PEDCELPDCAO PCP
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO,PROCODIGO2,PRODESCRICAO,PROUN FROM PRODU WHERE PROTIPO NOT IN ('T','S')) PD ON PD.PROCODIGO = RP.PROCODIGO

WHERE
PCP.ID_PEDIDO = :ID_PEDIDO AND
RP.PROCODIGO IS NOT NULL UNION

/* SELECIONA LENTES ACABADAS */

SELECT
  'CRICIUMA' EMPRESA,
  'PEDIDOS NAO ATENDIDOS' INDICADOR,
   PRD.ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   PRD.PROCODIGO MATERIAL , 
    PDPDESCRICAO NOME , 
      (SELECT DISTINCT PROUN FROM PRODU WHERE PROCODIGO=CHAVE ) UN,
      '' RQPSEQ,
      CHAVE CHAVE,
      (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE ) DESCRICAO_CHAVE,
      PRD.PDPQTDADE QTD    
      FROM PDPRD PRD
      INNER JOIN PED ON PRD.ID_PEDIDO=PED.ID_PEDIDO
      INNER JOIN PROD P ON PRD.PROCODIGO=P.PROCODIGO
  
  INTO :EMPRESA,:INDICADOR,:PEDIDO,:EMISSAO, :MATERIAL,:NOME, :UN,:SEQ,:CHAVE, :DESCRICAO_CHAVE,:QTD
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END 
  
  ")

#BC
fillrate_mp_bc_LA  <- dbGetQuery(con2,"
 EXECUTE BLOCK RETURNS ( 
                      EMPRESA VARCHAR(30), 
                       INDICADOR VARCHAR(30), 
                        PEDIDO INT,
                          EMISSAO DATE,   
                            MATERIAL VARCHAR(100),
                             NOME VARCHAR(100),
                              UN VARCHAR(30), 
                               SEQ VARCHAR(30),
                                CHAVE VARCHAR(30),
                                 DESCRICAO_CHAVE VARCHAR(100),
                                  QTD DECIMAL(15,2))
  
  AS DECLARE VARIABLE ID_PEDIDO INT;
  
  BEGIN
  FOR
  
    /* FILTRO PEDIDOS NAO ATENDIDOS BC */
  
WITH 
RESULT1 AS (SELECT DISTINCT P.ID_PEDIDO,PEDDTEMIS,AP.APCODIGO,LP.LPCODIGO FROM
PEDID P

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN (SELECT ID_PEDIDO FROM PEDID WHERE PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022') PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2) 
                  PR ON PR.PROCODIGO=PD.PROCODIGO) PRD ON P.ID_PEDIDO=PRD.ID_PEDIDO 
                  
LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 


/* DATES */ 

PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022'
--------------------------------------

AND
P.EMPCODIGO=8
AND TPCODIGO IN (1,2,3,6,7,12,14)
AND PEDSITPED IN ('A','F'))
 
 SELECT DISTINCT R.ID_PEDIDO
   FROM RESULT1 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )

  INTO :ID_PEDIDO 
  DO
  BEGIN
  FOR
  
   /* LENTES COM PRODUCAO */ 
  
  WITH PED AS (SELECT ID_PEDIDO,PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO),
  
  PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM 
  PRODU WHERE PROSITUACAO='A' AND PROTIPO NOT IN ('T','M','S','C'))
  
  SELECT
   'BC' EMPRESA,
   'PEDIDOS NAO ATENDIDOS' INDICADOR,
   ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   RP.PROCODIGO MATERIAL , 
    RP.RQPDESCRICAO NOME , 
     PD.PROUN UN,
      RQPSEQ,
      PD.PROCODIGO2 CHAVE,
      (SELECT DISTINCT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PD.PROCODIGO2) DESCRICAO_CHAVE,
      RP.RQPQTDADE QTD    
      FROM PEDCELPDCAO PCP
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO,PROCODIGO2,PRODESCRICAO,PROUN FROM PRODU WHERE PROTIPO NOT IN ('T','S')) PD ON PD.PROCODIGO = RP.PROCODIGO

WHERE
PCP.ID_PEDIDO = :ID_PEDIDO AND
RP.PROCODIGO IS NOT NULL 

UNION

/* SELECIONA LENTES ACABADAS */

SELECT
  'CRICIUMA' EMPRESA,
  'PEDIDOS NAO ATENDIDOS' INDICADOR,
   PRD.ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   PRD.PROCODIGO MATERIAL , 
    PDPDESCRICAO NOME , 
      (SELECT DISTINCT PROUN FROM PRODU WHERE PROCODIGO=CHAVE ) UN,
      '' RQPSEQ,
      CHAVE CHAVE,
      (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE ) DESCRICAO_CHAVE,
      PRD.PDPQTDADE QTD    
      FROM PDPRD PRD
      INNER JOIN PED ON PRD.ID_PEDIDO=PED.ID_PEDIDO
      INNER JOIN PROD P ON PRD.PROCODIGO=P.PROCODIGO
  
  INTO :EMPRESA,:INDICADOR,:PEDIDO,:EMISSAO, :MATERIAL,:NOME,:UN,:SEQ,:CHAVE, :DESCRICAO_CHAVE,:QTD
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END 
  
  ")



# CONTROL
fillrate_mp_control_LA  <- dbGetQuery(con2,"
 EXECUTE BLOCK RETURNS ( 
                      EMPRESA VARCHAR(30), 
                       INDICADOR VARCHAR(30), 
                        PEDIDO INT,
                          EMISSAO DATE,   
                            MATERIAL VARCHAR(100),
                             NOME VARCHAR(100),
                              UN VARCHAR(30), 
                               SEQ VARCHAR(30),
                                CHAVE VARCHAR(30),
                                 DESCRICAO_CHAVE VARCHAR(100),
                                  QTD DECIMAL(15,2))
  
  AS DECLARE VARIABLE ID_PEDIDO INT;
  
  BEGIN
  FOR
  
    /* FILTRO PEDIDOS CONTROL */
  
SELECT DISTINCT
   PE.ID_PEDIDO
FROM PEDID PE

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
               INNER JOIN (SELECT ID_PEDIDO FROM PEDID WHERE PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022') PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO

                INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2) 
                  PR ON PR.PROCODIGO=PD.PROCODIGO) PRD ON PE.ID_PEDIDO=PRD.ID_PEDIDO 

WHERE 

/* DATES */ 

PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022'
--------------------------------------

AND PE.PEDSITPED IN ('A','F')
AND PE.CLICODIGO IN (495,1065,81,5) AND PE.TPCODIGO IN ('10','11')
AND EXISTS (SELECT 1 FROM PEDROTEIRO PR1 WHERE PR1.ALXCODIGO = 1 AND PR1.ID_PEDIDO = PE.ID_PEDIDO)
AND NOT EXISTS (SELECT 1 FROM PEDROTEIRO PR2 WHERE PR2.ALXCODIGO IN ('15','16','10','9','38','40','6') 
AND PR2.ID_PEDIDO = PE.ID_PEDIDO) 

  INTO :ID_PEDIDO 
  DO
  BEGIN
  FOR
  
   /* LENTES COM PRODUCAO */ 
  
  WITH PED AS (SELECT ID_PEDIDO,CLICODIGO PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO),
  
  PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM 
  PRODU WHERE PROSITUACAO='A' AND PROTIPO NOT IN ('T','M','S','C'))
  
  SELECT
    (SELECT CASE 
  WHEN CLICODIGO=495 THEN 'JOINVILLE'
  WHEN CLICODIGO=1065 THEN 'CRICIUMA'
  WHEN CLICODIGO=81 THEN 'CHAPECO'
  WHEN CLICODIGO=5 THEN 'BALNEARIO C'
  END FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMPRESA,
   'PEDIDOS CONTROL FILIAIS' INDICADOR,
   ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   RP.PROCODIGO MATERIAL , 
    RP.RQPDESCRICAO NOME , 
     PD.PROUN UN,
      RQPSEQ,
      PD.PROCODIGO2 CHAVE,
      (SELECT DISTINCT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PD.PROCODIGO2) DESCRICAO_CHAVE,
      RP.RQPQTDADE QTD    
      FROM PEDCELPDCAO PCP
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO,PROCODIGO2,PRODESCRICAO,PROUN FROM PRODU WHERE PROTIPO NOT IN ('T','S')) PD ON PD.PROCODIGO = RP.PROCODIGO

WHERE
PCP.ID_PEDIDO = :ID_PEDIDO AND
RP.PROCODIGO IS NOT NULL 

UNION

/* SELECIONA LENTES ACABADAS */

SELECT
  
 (SELECT CASE 
  WHEN CLICODIGO=495 THEN 'JOINVILLE'
  WHEN CLICODIGO=1065 THEN 'CRICIUMA'
  WHEN CLICODIGO=81 THEN 'CHAPECO'
  WHEN CLICODIGO=5 THEN 'BALNEARIO C'
  END FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMPRESA,
  
  'PEDIDOS CONTROL' INDICADOR,
   PRD.ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   PRD.PROCODIGO MATERIAL , 
    PDPDESCRICAO NOME , 
      (SELECT DISTINCT PROUN FROM PRODU WHERE PROCODIGO=CHAVE ) UN,
      '' RQPSEQ,
      CHAVE CHAVE,
      (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE ) DESCRICAO_CHAVE,
      PRD.PDPQTDADE QTD    
      FROM PDPRD PRD
      INNER JOIN PED ON PRD.ID_PEDIDO=PED.ID_PEDIDO
      INNER JOIN PROD P ON PRD.PROCODIGO=P.PROCODIGO
  
  INTO :EMPRESA,:INDICADOR,:PEDIDO,:EMISSAO, :MATERIAL,:NOME,:UN,:SEQ,:CHAVE, :DESCRICAO_CHAVE,:QTD
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END 
  
  ")

# CONTROL NOT ATEND MATRIZ


fillrate_mp_control_matriz_LA  <- dbGetQuery(con2,"
  EXECUTE BLOCK RETURNS (
                        EMPRESA VARCHAR(30),
                         INDICADOR VARCHAR(30),
                          PEDIDO INT,
                           EMISSAO DATE,   
                            MATERIAL VARCHAR(100),
                             NOME VARCHAR(100),
                              UN VARCHAR(30), 
                               SEQ VARCHAR(30),
                                CHAVE VARCHAR(30),
                                 DESCRICAO_CHAVE VARCHAR(100),
                                  QTD DECIMAL(15,2))
  
  AS DECLARE VARIABLE ID_PEDIDO INT;
  
  BEGIN
  FOR
  
  /* FILTRO PEDIDOS NAO ATENDIDOS CONTROL MATRIZ */ 
  
WITH 
RESULT11 AS (SELECT DISTINCT P.ID_PEDIDO,PEDDTEMIS,AP.APCODIGO,LP.LPCODIGO FROM
PEDID P

/* FILTER LENS */  
INNER JOIN (SELECT DISTINCT PD.ID_PEDIDO
              FROM PDPRD PD
                INNER JOIN (SELECT ID_PEDIDO FROM PEDID WHERE PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022') PDT ON PD.ID_PEDIDO=PDT.ID_PEDIDO
                 INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE GR1CODIGO=2) 
                  PR ON PR.PROCODIGO=PD.PROCODIGO) PRD ON P.ID_PEDIDO=PRD.ID_PEDIDO 

LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO
LEFT JOIN LOCALPED LP ON LP.LPCODIGO  = AP.LPCODIGO 
WHERE 

/* DATES */ 

PEDDTEMIS >='23.01.2022' AND PEDDTEMIS <= '29.01.2022'
--------------------------------------

AND
P.EMPCODIGO=1
AND TPCODIGO IN (10,11)
AND PEDSITPED IN ('A','F'))
 
 SELECT DISTINCT R.ID_PEDIDO
   FROM RESULT11 R
   WHERE
      R.ID_PEDIDO > 0
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 69)
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )

  INTO :ID_PEDIDO 
  DO
  BEGIN
  FOR

  /* FILTRO PEDIDOS NAO ATENDIDOS MATRIZ */ 
  
  WITH PED AS (SELECT ID_PEDIDO,PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO),
  
      PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM PRODU WHERE PROSITUACAO='A' AND PROTIPO NOT IN ('T','M','S','C'))

  
  SELECT
   'MATRIZ' EMPRESA,
   'PEDIDOS CONTROL NAO ATENDIDOS' INDICADOR,
   ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   RP.PROCODIGO MATERIAL , 
    RP.RQPDESCRICAO NOME , 
     PD.PROUN UN , 
      RQPSEQ,
      PD.PROCODIGO2 CHAVE,
      (SELECT DISTINCT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PD.PROCODIGO2) DESCRICAO_CHAVE,
      RP.RQPQTDADE QTD    
      FROM PEDCELPDCAO PCP
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO,PROCODIGO2,PRODESCRICAO,PROUN FROM PRODU WHERE PROTIPO NOT IN ('T','S')) PD ON PD.PROCODIGO = RP.PROCODIGO

WHERE
PCP.ID_PEDIDO = :ID_PEDIDO AND
RP.PROCODIGO IS NOT NULL UNION

SELECT
  'MATRIZ' EMPRESA,
  'PEDIDOS CONTROL NAO ATENDIDOS' INDICADOR,
   PRD.ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   PRD.PROCODIGO MATERIAL , 
    PDPDESCRICAO NOME , 
      (SELECT DISTINCT PROUN FROM PRODU WHERE PROCODIGO=CHAVE ) UN,
      '' RQPSEQ,
      CHAVE CHAVE,
      (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE ) DESCRICAO_CHAVE,
      PRD.PDPQTDADE QTD    
      FROM PDPRD PRD
      INNER JOIN PED ON PRD.ID_PEDIDO=PED.ID_PEDIDO
      INNER JOIN PROD P ON PRD.PROCODIGO=P.PROCODIGO
  
  INTO :EMPRESA,:INDICADOR,:PEDIDO,:EMISSAO, :MATERIAL,:NOME, :UN, :SEQ,:CHAVE, :DESCRICAO_CHAVE,:QTD
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END 
  
  ")

# ADD ALL BLOCKS

fillrate_mp_emp_LA <- union_all(fillrate_mp_matriz_LA,fillrate_mp_joinville_LA) %>% 
  union_all(.,fillrate_mp_criciuma_LA) %>% 
  union_all(.,fillrate_mp_chapeco_LA) %>% 
  union_all(.,fillrate_mp_bc_LA) %>% 
  union_all(.,fillrate_mp_control_LA) %>% 
  union_all(.,fillrate_mp_control_matriz_LA) %>% 
  mutate(DATA='23.01.2022 - 29.01.2022') %>% distinct() %>% as.data.frame()


# SAVE CURRENT DAY

filewd_emp_LA <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_mp_emp_LA","_",format(Sys.Date(),"%d_%m_%y"),".RData")

save(fillrate_mp_emp_LA,file =filewd_emp_LA)


# AGGREG MP AND SUM

fillrate_mp_emp_resumo_LA <- fillrate_mp_emp_LA %>% group_by(INDICADOR,CHAVE,DESCRICAO_CHAVE) %>% 
  summarize(QTD=sum(QTD)) %>% 
  arrange(desc(QTD)) %>% 
  mutate(DATA='23.01.2022 - 29.01.2022') %>%  as.data.frame()

filewd_emp_resumo_LA <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_mp_emp_resumo_LA","_",format(Sys.Date(),"%d_%m_%y"),".RData")


save(fillrate_mp_emp_resumo_LA,file =filewd_emp_resumo_LA)


##  SEND EMAIL  ==============================================================================================

library(gmailr)
library(xlsx)

gm_auth_configure(path = "C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\sendmail.json")


#RESUMO
filewd_fillrate_resumo_LA <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_resumo_2_LA","_",format(Sys.Date(),"%d_%m_%y"),".RData")

fillrate_resumo_LA <- get(load(filewd_fillrate_resumo_LA)) %>% as.data.frame()

#CALCULO
filewd_fillrate_calc_LA <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_calc_LA","_",format(Sys.Date(),"%d_%m_%y"),".RData")

fillrate_calc_LA <- get(load(filewd_fillrate_calc_LA))

#DADOS MP
filewd_emp_LA <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_mp_emp_LA","_",format(Sys.Date(),"%d_%m_%y"),".RData")

fillrate_mp_emp_LA <- get(load(filewd_emp_LA))

## RESUMO MP
filewd_emp_resumo_LA <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_mp_emp_resumo_LA","_",format(Sys.Date(),"%d_%m_%y"),".RData")

fillrate_mp_emp_resumo_LA <- get(load(filewd_emp_resumo_LA))


filewd_emp_mail_LA <-  paste0("C:\\Users\\Repro\\Documents\\R\\LOGISTICA\\FILLRATE\\BASES\\fillrate_mp_emp_LA_02.01.2022 - 08.01.2022.xlsx")

write.xlsx(fillrate_resumo_LA, file = filewd_emp_mail_LA,row.names=FALSE,sheetName = "RESUMO",showNA=FALSE)
write.xlsx(fillrate_calc_LA, file = filewd_emp_mail_LA,row.names=FALSE,sheetName = "CALCULO_FILLRATE",showNA=FALSE,append = TRUE)
write.xlsx(fillrate_mp_emp_LA, file = filewd_emp_mail_LA,row.names=FALSE,sheetName = "DADOS", append = TRUE)
write.xlsx(fillrate_mp_emp_resumo_LA, file = filewd_emp_mail_LA,row.names=FALSE,sheetName = "DADOS2", append = TRUE)



mymail_fillrate_LA <- gm_mime() %>% 
  gm_to("sandro.jakoska@repro.com.br,silvano.silva@repro.com.br") %>% 
  gm_from ("comunicacao@repro.com.br") %>%
  gm_subject("RELATORIO FILL RATE LENTES ACABADAS SEMANA 4 - 23/01/2022 - 29/01/2022") %>%
  gm_text_body("Segue Anexo relatorio SEMANA 4 - 23/01/2022 - 29/01/2022") %>% 
  gm_attach_file(filewd_emp_mail_LA) 

gm_send_message(mymail_fillrate_LA)
