 EXECUTE BLOCK RETURNS ( 
                      EMPRESA VARCHAR(30), 
                       INDICADOR VARCHAR(30), 
                        PEDIDO INT,
                          EMISSAO DATE,   
                            MATERIAL VARCHAR(100),
                             NOME VARCHAR(100),
                              UN VARCHAR(30), 
                               SEQ VARCHAR(30),
                                CHAVE VARCHAR(30),
                                 DESCRICAO_CHAVE VARCHAR(100),
                                  QTD DECIMAL(15,2))
  
  AS DECLARE VARIABLE ID_PEDIDO INT;
  
  BEGIN
  FOR
  
    /* FILTRO PEDIDOS CONTROL */
  
SELECT DISTINCT
   PE.ID_PEDIDO
FROM PEDID PE

/* FILTRA BLOCOS */  

INNER JOIN (SELECT
DISTINCT
PCP.ID_PEDIDO
FROM PEDCELPDCAO PCP
INNER JOIN (SELECT ID_PEDIDO FROM PEDID WHERE PEDDTEMIS >=DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY') PDT ON PCP.ID_PEDIDO=PDT.ID_PEDIDO
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE PROCODIGO2 IN 
('MF0317','MF0322','MF0323','MF0385','MF0391','MF0396','MF0397','MF0398','MF0399',
'MF0404','MF0405','MF0417','MF0418','MF0419','MF0426'))PR ON RP.PROCODIGO=PR.PROCODIGO) PRD ON PE.ID_PEDIDO=PRD.ID_PEDIDO 

WHERE 

/* DATES */ 

PEDDTEMIS >=DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'
--------------------------------------

AND PE.PEDSITPED IN ('A','F')
AND PE.CLICODIGO IN (495,1065,81,5) AND PE.TPCODIGO IN ('10','11')
AND EXISTS (SELECT 1 FROM PEDROTEIRO PR1 WHERE PR1.ALXCODIGO = 1 AND PR1.ID_PEDIDO = PE.ID_PEDIDO)
AND NOT EXISTS (SELECT 1 FROM PEDROTEIRO PR2 WHERE PR2.ALXCODIGO IN ('15','16','10','9','38','40','6') 
AND PR2.ID_PEDIDO = PE.ID_PEDIDO) 

  INTO :ID_PEDIDO 
  DO
  BEGIN
  FOR
  
   /* LENTES COM PRODUCAO */ 
  
  WITH PED AS (SELECT ID_PEDIDO,CLICODIGO PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO),
  
  PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM 
  PRODU WHERE PROSITUACAO='A' AND PROTIPO NOT IN ('T','M','S','C'))
  
  SELECT
    (SELECT CASE 
  WHEN CLICODIGO=495 THEN 'JOINVILLE'
  WHEN CLICODIGO=1065 THEN 'CRICIUMA'
  WHEN CLICODIGO=81 THEN 'CHAPECO'
  WHEN CLICODIGO=5 THEN 'BALNEARIO C'
  END FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMPRESA,
   'PEDIDOS CONTROL FILIAIS' INDICADOR,
   ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   RP.PROCODIGO MATERIAL , 
    RP.RQPDESCRICAO NOME , 
     PD.PROUN UN,
      RQPSEQ,
      PD.PROCODIGO2 CHAVE,
      (SELECT DISTINCT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PD.PROCODIGO2) DESCRICAO_CHAVE,
      RP.RQPQTDADE QTD    
      FROM PEDCELPDCAO PCP
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO,PROCODIGO2,PRODESCRICAO,PROUN FROM PRODU WHERE PROTIPO NOT IN ('T','S')) PD ON PD.PROCODIGO = RP.PROCODIGO

WHERE
PCP.ID_PEDIDO = :ID_PEDIDO AND
RP.PROCODIGO IS NOT NULL 

UNION

/* SELECIONA LENTES ACABADAS */

SELECT
  
 (SELECT CASE 
  WHEN CLICODIGO=495 THEN 'JOINVILLE'
  WHEN CLICODIGO=1065 THEN 'CRICIUMA'
  WHEN CLICODIGO=81 THEN 'CHAPECO'
  WHEN CLICODIGO=5 THEN 'BALNEARIO C'
  END FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMPRESA,
  
  'PEDIDOS CONTROL' INDICADOR,
   PRD.ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   PRD.PROCODIGO MATERIAL , 
    PDPDESCRICAO NOME , 
      (SELECT DISTINCT PROUN FROM PRODU WHERE PROCODIGO=CHAVE ) UN,
      '' RQPSEQ,
      CHAVE CHAVE,
      (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE ) DESCRICAO_CHAVE,
      PRD.PDPQTDADE QTD    
      FROM PDPRD PRD
      INNER JOIN PED ON PRD.ID_PEDIDO=PED.ID_PEDIDO
      INNER JOIN PROD P ON PRD.PROCODIGO=P.PROCODIGO
  
  INTO :EMPRESA,:INDICADOR,:PEDIDO,:EMISSAO, :MATERIAL,:NOME,:UN,:SEQ,:CHAVE, :DESCRICAO_CHAVE,:QTD
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END