WITH PED_DATE AS (SELECT ID_PEDIDO FROM PEDID WHERE
PEDDTEMIS >=DATEADD(-7 DAY TO CURRENT_DATE) AND PEDDTEMIS < 'TODAY'),

RESULT1 AS (SELECT P.ID_PEDIDO,TPCODIGO,AP.APCODIGO FROM
PEDID P
INNER JOIN PED_DATE PDT ON P.ID_PEDIDO=PDT.ID_PEDIDO

/* FILTRA BLOCOS */  
INNER JOIN (SELECT
DISTINCT
PCP.ID_PEDIDO
FROM PEDCELPDCAO PCP
INNER JOIN PED_DATE PDT ON PCP.ID_PEDIDO=PDT.ID_PEDIDO
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE PROCODIGO2 IN 
('MF0317','MF0322','MF0323','MF0385','MF0391','MF0396','MF0397','MF0398','MF0399',
'MF0404','MF0405','MF0417','MF0418','MF0419','MF0426'))PR ON RP.PROCODIGO=PR.PROCODIGO) PRD ON P.ID_PEDIDO=PRD.ID_PEDIDO 

LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO

WHERE 

P.EMPCODIGO=1
AND TPCODIGO IN (1,2,3,6,7,12,14)
AND PEDSITPED IN ('A','F') ),

RESULT3 AS (SELECT P.ID_PEDIDO,TPCODIGO,AP.APCODIGO FROM
PEDID P
INNER JOIN PED_DATE PDT ON P.ID_PEDIDO=PDT.ID_PEDIDO

/* FILTRA BLOCOS */  

INNER JOIN (SELECT
DISTINCT
PCP.ID_PEDIDO
FROM PEDCELPDCAO PCP
INNER JOIN PED_DATE PDT ON PCP.ID_PEDIDO=PDT.ID_PEDIDO
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE PROCODIGO2 IN 
('MF0317','MF0322','MF0323','MF0385','MF0391','MF0396','MF0397','MF0398','MF0399',
'MF0404','MF0405','MF0417','MF0418','MF0419','MF0426'))PR ON RP.PROCODIGO=PR.PROCODIGO) PRD ON P.ID_PEDIDO=PRD.ID_PEDIDO 

LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO


WHERE 

P.EMPCODIGO=3
AND TPCODIGO IN (1,3)
AND PEDSITPED IN ('A','F') ),

RESULT4 AS (SELECT P.ID_PEDIDO,TPCODIGO,AP.APCODIGO FROM
PEDID P
INNER JOIN PED_DATE PDT ON P.ID_PEDIDO=PDT.ID_PEDIDO

/* FILTRA BLOCOS */  

INNER JOIN (SELECT
DISTINCT
PCP.ID_PEDIDO
FROM PEDCELPDCAO PCP
INNER JOIN PED_DATE PDT ON PCP.ID_PEDIDO=PDT.ID_PEDIDO
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE PROCODIGO2 IN 
('MF0317','MF0322','MF0323','MF0385','MF0391','MF0396','MF0397','MF0398','MF0399',
'MF0404','MF0405','MF0417','MF0418','MF0419','MF0426'))PR ON RP.PROCODIGO=PR.PROCODIGO) PRD ON P.ID_PEDIDO=PRD.ID_PEDIDO 

LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO


WHERE 

P.EMPCODIGO=4
AND TPCODIGO IN (1,3)
AND PEDSITPED IN ('A','F') ),

RESULT5 AS (SELECT P.ID_PEDIDO,TPCODIGO,AP.APCODIGO FROM
PEDID P
INNER JOIN PED_DATE PDT ON P.ID_PEDIDO=PDT.ID_PEDIDO

/* FILTRA BLOCOS */  

INNER JOIN (SELECT
DISTINCT
PCP.ID_PEDIDO
FROM PEDCELPDCAO PCP
INNER JOIN PED_DATE PDT ON PCP.ID_PEDIDO=PDT.ID_PEDIDO
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE PROCODIGO2 IN 
('MF0317','MF0322','MF0323','MF0385','MF0391','MF0396','MF0397','MF0398','MF0399',
'MF0404','MF0405','MF0417','MF0418','MF0419','MF0426'))PR ON RP.PROCODIGO=PR.PROCODIGO) PRD ON P.ID_PEDIDO=PRD.ID_PEDIDO 

LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO

WHERE 

P.EMPCODIGO=5
AND TPCODIGO IN (1,3)
AND PEDSITPED IN ('A','F') ),

RESULT8 AS (SELECT P.ID_PEDIDO,TPCODIGO,AP.APCODIGO FROM
PEDID P
INNER JOIN PED_DATE PDT ON P.ID_PEDIDO=PDT.ID_PEDIDO

/* FILTRA BLOCOS */ 

INNER JOIN (SELECT
DISTINCT
PCP.ID_PEDIDO
FROM PEDCELPDCAO PCP
INNER JOIN PED_DATE PDT ON PCP.ID_PEDIDO=PDT.ID_PEDIDO
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE PROCODIGO2 IN 
('MF0317','MF0322','MF0323','MF0385','MF0391','MF0396','MF0397','MF0398','MF0399',
'MF0404','MF0405','MF0417','MF0418','MF0419','MF0426'))PR ON RP.PROCODIGO=PR.PROCODIGO) PRD ON P.ID_PEDIDO=PRD.ID_PEDIDO 

LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO

WHERE 

P.EMPCODIGO=8
AND TPCODIGO IN (1,3,9)
AND PEDSITPED IN ('A','F')),

RESULT9 AS (SELECT P.ID_PEDIDO,TPCODIGO,AP.APCODIGO FROM
PEDID P
INNER JOIN PED_DATE PDT ON P.ID_PEDIDO=PDT.ID_PEDIDO

/* FILTRA BLOCOS */  

INNER JOIN (SELECT
DISTINCT
PCP.ID_PEDIDO
FROM PEDCELPDCAO PCP
INNER JOIN PED_DATE PDT ON PCP.ID_PEDIDO=PDT.ID_PEDIDO
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO FROM PRODU WHERE PROCODIGO2 IN 
('MF0317','MF0322','MF0323','MF0385','MF0391','MF0396','MF0397','MF0398','MF0399',
'MF0404','MF0405','MF0417','MF0418','MF0419','MF0426'))PR ON RP.PROCODIGO=PR.PROCODIGO) PRD ON P.ID_PEDIDO=PRD.ID_PEDIDO 

LEFT JOIN ACOPED AP ON AP.ID_PEDIDO= P.ID_PEDIDO

WHERE 

P.EMPCODIGO=1
AND TPCODIGO IN (10,11)
AND PEDSITPED IN ('A','F'))

 /* SELECT BY EMP */ 
 
 SELECT 'MATRIZ' EMPRESA,TPCODIGO TIPO,'TOTAL PEDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT1 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
      GROUP BY 1,2,3 UNION
    
      
    SELECT 'JOINVILLE' EMPRESA,TPCODIGO TIPO,'TOTAL PEDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT3 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 ) 
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
      GROUP BY 1,2,3 UNION
      
     SELECT 'CRICIUMA' EMPRESA,TPCODIGO TIPO,'TOTAL PEDIDOS' INDICADOR, COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT4 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
      GROUP BY 1,2,3 UNION
      
      SELECT 'CHAPECO' EMPRESA,TPCODIGO TIPO,'TOTAL PEDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT5 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
      GROUP BY 1,2,3 UNION
      
      SELECT 'BALNEARIO C' EMPRESA,TPCODIGO TIPO,'TOTAL PEDIDOS' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT8 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
      GROUP BY 1,2,3 UNION
      
      SELECT 'MATRIZ' EMPRESA,TPCODIGO TIPO,'TOTAL PEDIDOS CONTROL' INDICADOR,COUNT(DISTINCT R.ID_PEDIDO) TOTAL
   FROM RESULT9 R
   WHERE
      R.ID_PEDIDO > 0 
      AND R.APCODIGO = (SELECT MAX(APCODIGO) FROM ACOPED APO 
      LEFT JOIN LOCALPED LP2 ON APO.LPCODIGO = LP2.LPCODIGO 
      WHERE APO.ID_PEDIDO = R.ID_PEDIDO )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1805 )
      AND NOT EXISTS (SELECT 1 FROM ACOPED ACP WHERE ACP.ID_PEDIDO= R.ID_PEDIDO AND ACP.LPCODIGO = 1847 )
      GROUP BY 1,2,3